### ISSUE TITLE
Monitoring integration should monitor host status

### ISSUE THREAD

**Issue by nnDarshan** [Tendrl/monitoring-integration#123]
node context object has a status attribute, whose value will be `UP` if node is up and running. Whenever node goes down, the status attribute will vanish due to ttl set on the attribute. Monitoring integration should use this attribute to determine the host status and use it appropriately

**Comment by rishubhjain** [comment]
@nnDarshan I guess this is not needed anymore, can you close this issue?

**Comment by nnDarshan** [comment]
Not needed anymore as plan is to update the status as down in node-agent itself
