### ISSUE TITLE
Configuration file monitoring-integration.conf.yaml with etcd root password is readable for every account

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/monitoring-integration#125]
## Description

Configuration file `/etc/tendrl/monitoring-integration/monitoring-integration.conf.yaml` can now contain username and password for etcd admin access, but the file is still packaged as world readable.

## Version

Latest snapshot build from master branch (it's part of [upcoming 1.5.2 version](https://github.com/Tendrl/specifications/milestone/1)):

```
tendrl-monitoring-integration-1.5.2-20170918T072405.e742bba.noarch
```

## Steps to Reproduce

1. Prepare machines with GlusterFS cluster, including gluster volume (I used [nightly builds](https://github.com/usmqe/usmqe-setup/tree/master/roles/gluster-centos-repo) and [volume_usmqe_alpha_distrep_4x2.create.conf](https://github.com/usmqe/usmqe-setup/blob/master/gdeploy_config/volume_usmqe_alpha_distrep_4x2.create.conf))
2. Install Tendrl via tendrl-ansible there, using [snapshot builds](https://copr.fedorainfracloud.org/coprs/tendrl/tendrl/)
3. Log into tendrl server machine via ssh
4. Check access rights of `monitoring-integration.conf.yaml` config file:

```
# ls -l /etc/tendrl/monitoring-integration/monitoring-integration.conf.yaml
```

5. Check that the access rights are not changed compared to packaged defaults:

```
# rpm -qcV tendrl-monitoring-integration
```

## Actual Results

The config file is world readable, which is default packaged state:

```
# ls -l /etc/tendrl/monitoring-integration/monitoring-integration.conf.yaml
-rw-r--r--. 1 root root 1335 Sep 18 13:01 /etc/tendrl/monitoring-integration/monitoring-integration.conf.yaml
# rpm -qcV tendrl-monitoring-integration
......G..  c /etc/tendrl/monitoring-integration/grafana/grafana.ini
S.5....T.  c /etc/tendrl/monitoring-integration/monitoring-integration.conf.yaml
```

Note: the last line states that `S` (file Size differs), `5` (digest (formerly MD5 sum) differ) and `T` (mTime differs). Which means that the access rights were not changed since installation.

## Expected Results

The access rights of the config file are either user only or user/group readable.

## Additional Details

As you can see, the etcd root password is stored in given file:

```
# grep etcd_password /etc/tendrl/monitoring-integration/monitoring-integration.conf.yaml
etcd_password: twZONmWfcaSJayIlIzrQaNyBhusDVx
```

## See Also

The same issues in different Tendrl components:

* https://github.com/Tendrl/node-agent/issues/625
* https://github.com/Tendrl/api/issues/293

**Comment by mbukatov** [comment]
When I noticed this problem in one case, I run the following commands on both Tendrl Server and Tendrl Storage Node machines to find out all affected Tendrl components:

```
# rpm -qa | grep tendrl | xargs rpm -qc | xargs grep twZONmWfcaSJayIlIzrQaNyBhusDVx
/etc/tendrl/etcd.yml:  :password: 'twZONmWfcaSJayIlIzrQaNyBhusDVx'
/etc/tendrl/etcd.yml:  :password: 'twZONmWfcaSJayIlIzrQaNyBhusDVx'
/etc/tendrl/etcd.yml:  :password: 'twZONmWfcaSJayIlIzrQaNyBhusDVx'
/etc/tendrl/node-agent/node-agent.conf.yaml:etcd_password: twZONmWfcaSJayIlIzrQaNyBhusDVx
/etc/tendrl/monitoring-integration/monitoring-integration.conf.yaml:etcd_password: twZONmWfcaSJayIlIzrQaNyBhusDVx
# rpm -qa | grep tendrl | xargs rpm -qc | xargs grep twZONmWfcaSJayIlIzrQaNyBhusDVx | cut -d: -f1 | sort | uniq | xargs ls -l
-rw-r--r--. 1 root root  405 Sep 18 12:58 /etc/tendrl/etcd.yml
-rw-r--r--. 1 root root 1335 Sep 18 13:01 /etc/tendrl/monitoring-integration/monitoring-integration.conf.yaml
-rw-r--r--. 1 root root  696 Sep 18 12:57 /etc/tendrl/node-agent/node-agent.conf.yaml
```

As you can see, all config files with the password are readable for every local unix account.

**Comment by rishubhjain** [comment]
@r0h4n I would like to know what changes I need to make to solve this issue.

**Comment by rishubhjain** [comment]
@mbukatov can we close this issue?

**Comment by rishubhjain** [comment]
@mbukatov monitoring-integration.conf.yaml is read by monitoring-integration as well, so I am afraid changing the permission might block this read. Could you test Monitoring-integration again with this change?

I tested it my local machine, the service needs root privilege to work as per expectation.

**Comment by mbukatov** [comment]
@rishubhjain does it mean we should make the config files to belong to tendrl unix group?

**Comment by rishubhjain** [comment]
Ya I think so, may be we can test it to see whether its running without making any other change.
I will also test on a VM to be sure

**Comment by r0h4n** [comment]
Umm, tendrl services are assumed to be run as root. So i think no further changes are required

**Comment by rishubhjain** [comment]
@mbukatov In that case I guess this issue is fixed, @mbukatov Please verify and close this issue

**Comment by mbukatov** [comment]
Verifying with `tendrl-monitoring-integration-1.5.2-20170926T072406.6f3f855.noarch`:

```
# ls -l /etc/tendrl/monitoring-integration/monitoring-integration.conf.yaml /etc/tendrl/monitoring-integration/grafana/grafana.ini
-rw-r-----. 1 root grafana 11921 Sep 26 05:56 /etc/tendrl/monitoring-integration/grafana/grafana.ini
-rw-r-----. 1 root root     1358 Sep 26 05:56 /etc/tendrl/monitoring-integration/monitoring-integration.conf.yaml
```

Additional check doesn't show any problems either:

```
# rpm -qa | grep tendrl | xargs rpm -qc | xargs grep afnhRjtdDOWUGVYgdhuFCajXPbgIGu | cut -d: -f1 | sort | uniq | xargs ls -l
-rw-r-----. 1 root grafana 11921 Sep 26 05:56 /etc/tendrl/monitoring-integration/grafana/grafana.ini
-rw-r-----. 1 root root     1358 Sep 26 05:56 /etc/tendrl/monitoring-integration/monitoring-integration.conf.yaml
```

And yes, the service runs under root right now:

```
# ps aux | grep tendrl-monitoring-integration | grep -v grep
root      9171 33.4  0.2 494908 31636 ?        Ssl  05:57  41:30 /usr/bin/python /usr/bin/tendrl-monitoring-integration
```
