### ISSUE TITLE
No need to copy logging.yaml.timedrotation.sample while installing monitoring_integration

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/monitoring-integration#134]
Log functionalities are happening only in node agent, monitoring_integration is passing the log messages to node_agent and node_agent is actually doing logging. So no need to maintain logging.yaml.timedrotation.sample in monitoring integration.

**Comment by rishubhjain** [comment]
@GowthamShanmugam The PR is merged, please close the issue

**Comment by GowthamShanmugam** [comment]
@rishubhjain ok

**Comment by GowthamShanmugam** [comment]
@rishubhjain this issue is fixed, So I am closing this
