### ISSUE TITLE
Need to add this repository in coverall and codacy 3rd party tools to calculate code quality

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/monitoring-integration#143]

**Comment by GowthamShanmugam** [comment]
@rishubhjain @r0h4n

**Comment by rishubhjain** [comment]
@GowthamShanmugam Please close the issue, the PR is merged

**Comment by GowthamShanmugam** [comment]
@rishubhjain this should be comment by @r0h4n after that only I can close

**Comment by rishubhjain** [comment]
@r0h4n Verification needed before deleting this issue

**Comment by rishubhjain** [comment]
@r0h4n Please close the issue

**Comment by GowthamShanmugam** [comment]
i am closing this issue
