### ISSUE TITLE
5 from 6 nodes are down and grafana doens't reflect it

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/monitoring-integration#145]
I have cluster with 6 nodes and I've turn off 5 of them. Some charts in Grafana dashboards don't reflect that, please see screenshots. There is only one volume.

Here should be marked that one volume as *Partial* and 10 from 12 bricks should be down.
![bugdown_at_glance1](https://user-images.githubusercontent.com/5920442/30864078-f06a8700-a2d2-11e7-9119-423ef21b5225.png)

Only *gl1* machine is up so others should be marked as down.
![bugdown_at_glance2](https://user-images.githubusercontent.com/5920442/30864162-29343c66-a2d3-11e7-9f1a-915bc35f0912.png)

Bricks dashboard doesn't show by default relevant info.
![bugdown_bricks](https://user-images.githubusercontent.com/5920442/30864222-4ef62022-a2d3-11e7-80fa-4670e6566523.png)

Here is *host dashboard* for hosts which is down at 2 screenshots. Marked charts should show *NA* because host is down.
![bugdown_hosts](https://user-images.githubusercontent.com/5920442/30864403-c59ad290-a2d3-11e7-96b4-73cf7c5b1646.png)

 Marked charts should show *NA* because right now they show *Zero* which is not right value. 
![bugdown_hosts2](https://user-images.githubusercontent.com/5920442/30864305-7a997f44-a2d3-11e7-84fa-f991520c1ca8.png)

Volume dashboard should reflect that 5 from 6 nodes are down.
![bugdown_volumes](https://user-images.githubusercontent.com/5920442/30864497-1133d1f2-a2d4-11e7-8ba3-dc042baed516.png)

**Comment by rishubhjain** [comment]
@mkudlej Thanks for reporting the issue, There are some details I require to debug this issue.
Whats the time interval between turning off nodes and checking the dashboards in grafana?

**Comment by mkudlej** [comment]
I've forgotten to input here list of pkgs:
```
etcd-3.2.5-1.el7.x86_64
python-etcd-0.4.5-1.noarch
rubygem-etcd-0.3.0-1.el7.centos.noarch
tendrl-api-1.5.2-20170921T125939.61d8945.noarch
tendrl-api-httpd-1.5.2-20170921T125939.61d8945.noarch
tendrl-commons-1.5.2-20170921T220225.c77a8fc.noarch
tendrl-grafana-plugins-1.5.2-20170925T072405.6f3f855.noarch
tendrl-monitoring-integration-1.5.2-20170925T072405.6f3f855.noarch
tendrl-node-agent-1.5.2-20170922T094941.ced9876.noarch
tendrl-notifier-1.5.2-20170922T082559.b6a2768.noarch
tendrl-ui-1.5.2-20170921T165116.b85723e.noarch
```

Time between turning off machines and these screenshots is more than 2 days.

**Comment by rishubhjain** [comment]
@mkudlej if possible please update node-agent on each nodes. The nodes now have ttl which deletes the nodes from etcd if the node is removed.
Please also inform if you are able to reproduce this issue after updating node-agents

**Comment by mkudlej** [comment]
I see change with (last packages from today master)
```
etcd-3.2.5-1.el7.x86_64
grafana-4.5.2-1.x86_64
python-etcd-0.4.5-1.noarch
rubygem-etcd-0.3.0-1.el7.centos.noarch
tendrl-api-1.5.2-20170927T205654.a9e16c0.noarch
tendrl-api-httpd-1.5.2-20170927T205654.a9e16c0.noarch
tendrl-commons-1.5.2-20171004T104238.6d5ffef.noarch
tendrl-gluster-integration-1.5.2-20171004T141256.07ceba5.noarch
tendrl-grafana-plugins-1.5.2-20171004T072405.2e1d15a.noarch
tendrl-monitoring-integration-1.5.2-20171004T072405.2e1d15a.noarch
tendrl-node-agent-1.5.2-20171004T105957.709badc.noarch
tendrl-notifier-1.5.2-20170927T205657.566bfa0.noarch
tendrl-ui-1.5.2-20170928T151925.1cdc907.noarch
```
but still info in charts is not correct.
Issues:
### at-glance dashboard
1) wrong hosts chart: ```Total: 6, Up:5, Down:0 - colour green```
2) wrong volumes chart: ```Total: 1, Degraded:0, Down:1``` It should be ```Total:1, Degraded: 1, Down: 0```
3) wrong bricks chart: ```Total: 12, Up: 12, Down:0``` which should be ```Total: 12, Up: 10, Down: 2```
4) Bugs from picture https://user-images.githubusercontent.com/5920442/30864162-29343c66-a2d3-11e7-9f1a-915bc35f0912.png remain.

### bricks dashboard
1) Bugs from https://user-images.githubusercontent.com/5920442/30864222-4ef62022-a2d3-11e7-80fa-4670e6566523.png remain.

### hosts dashboard for gl6 which is off
1) memory free chart - missing "No data points" message
2) swap utilization - missing "No data points" message
3) bricks: ```Total: 2, Up: 2, Down: 0``` - it should be ```Total: 2, Up: 0, Down: 2``` - in red colour
4) IOPS - missing "No data points" message
5) CPU utilization - missing "No data points" message
6) Bricks status - similar to 3)
7) Total brick capacity utilization trend - missing "No data points" message
8) Throughput - missing "No data points" message
9) Dropped packets pre second - missing "No data points" message
10) errors per second - missing "No data points" message

### volume dashboard
1) Health is ```UP``` but it should be ```Degraded```
2) Bricks - ```Total: 14, Up: 14, Down:0``` and it should be ```Total: 12, Up:10, Down:2```
3) Brick status - does not reflect that gl6 is down

Could you please write here list of packages once **all** these issues are fixed or break this issue into smaller issues according your opinion?

**Comment by shtripat** [comment]
There was an issue with node sync from monitoring-integration. The same is corrected and PR is sent.

**Comment by r0h4n** [comment]
@shtripat @rishubhjain Is the PR verified to fix the host status issue?

**Comment by rishubhjain** [comment]
@mkudlej Thank you for reporting the issue, Here's an update on the issue:
1) Regarding the host not being down even after getting disconnected:
    https://github.com/Tendrl/monitoring-integration/pull/168 Solves that particular issue. If possible 
    please verify it by updating tendrl-monitoring-integration and restarting it.

2) Regarding Volume showing down instead of degraded:
    We are working on debugging the issue, In my opinion solution to 
    https://github.com/Tendrl/monitoring-integration/issues/167 will solve that particular issue.

3) Regarding Brick chart not showing proper values:
    We are working on a solution for it, you can follow https://github.com/Tendrl/monitoring-
    integration/issues/169 for updates regarding same.

**Comment by rishubhjain** [comment]
@r0h4n Yes, the PR is merged and has been tested. But it solves only the host status issue.

**Comment by rishubhjain** [comment]
@mkudlej I have addressed all the issues mentioned, Please check whether any issue mentioned above are reproducable.

**Comment by mkudlej** [comment]
@rishubhjain In which set of packages are fixed issues described here? Because with
```
etcd-3.2.5-1.el7.x86_64
glusterfs-4.0dev-0.213.git09f6ae2.el7.centos.x86_64
glusterfs-4.0dev-0.218.git614904f.el7.centos.x86_64
glusterfs-api-4.0dev-0.218.git614904f.el7.centos.x86_64
glusterfs-cli-4.0dev-0.218.git614904f.el7.centos.x86_64
glusterfs-client-xlators-4.0dev-0.213.git09f6ae2.el7.centos.x86_64
glusterfs-client-xlators-4.0dev-0.218.git614904f.el7.centos.x86_64
glusterfs-events-4.0dev-0.218.git614904f.el7.centos.x86_64
glusterfs-fuse-4.0dev-0.213.git09f6ae2.el7.centos.x86_64
glusterfs-fuse-4.0dev-0.218.git614904f.el7.centos.x86_64
glusterfs-geo-replication-4.0dev-0.218.git614904f.el7.centos.x86_64
glusterfs-libs-4.0dev-0.213.git09f6ae2.el7.centos.x86_64
glusterfs-libs-4.0dev-0.218.git614904f.el7.centos.x86_64
glusterfs-server-4.0dev-0.218.git614904f.el7.centos.x86_64
python2-gluster-4.0dev-0.218.git614904f.el7.centos.x86_64
python-etcd-0.4.5-1.noarch
rubygem-etcd-0.3.0-1.el7.centos.noarch
tendrl-ansible-1.5.3-20171016T154931.c64462a.noarch
tendrl-api-1.5.3-20171013T082716.a2f3b3f.noarch
tendrl-api-httpd-1.5.3-20171013T082716.a2f3b3f.noarch
tendrl-commons-1.5.3-20171017T094335.9050aa7.noarch
tendrl-gluster-integration-1.5.3-20171013T082052.b8ddae5.noarch
tendrl-grafana-plugins-1.5.3-20171016T100950.e8eb6c8.noarch
tendrl-grafana-selinux-1.5.3-20171013T090621.ffb1b7f.noarch
tendrl-monitoring-integration-1.5.3-20171016T100950.e8eb6c8.noarch
tendrl-node-agent-1.5.3-20171016T094453.4aa81f7.noarch
tendrl-notifier-1.5.3-20171011T200310.3c01717.noarch
tendrl-selinux-1.5.3-20171013T090621.ffb1b7f.noarch
tendrl-ui-1.5.3-20171016T141509.544015a.noarch
```
I still see some already described issues.

**Comment by r0h4n** [comment]
Closing this, @mkudlej  please file individual bugs if any issues persists.
