### ISSUE TITLE
Capacity row is not separated in Volumes dashboard

### ISSUE THREAD

**Issue by fbalak** [Tendrl/monitoring-integration#147]
In specification for [Volumes dashboard](https://github.com/Tendrl/specifications/issues/224) is row Capacity separated by title from At-a-glance row.In [Metrics documentation](https://github.com/Tendrl/documentation/wiki/Metrics) and in the implemented ui they are not separated:

![926_separetedrows](https://user-images.githubusercontent.com/22369801/30870524-5627450e-a2e4-11e7-949b-66e767fb4325.png)

Tested with:
```
tendrl-api-httpd-1.5.2-20170926T110841.a9e16c0.noarch
tendrl-commons-1.5.2-20170926T081245.0fa5e25.noarch
tendrl-api-1.5.2-20170926T110841.a9e16c0.noarch
tendrl-ui-1.5.2-20170926T100141.770936f.noarch
tendrl-node-agent-1.5.2-20170926T090753.09d1818.noarch
tendrl-monitoring-integration-1.5.2-20170926T100202.2e1d15a.noarch
tendrl-grafana-plugins-1.5.2-20170926T100202.2e1d15a.noarch
tendrl-notifier-1.5.2-20170926T102449.7678c47.noarch
```

**Comment by nthomas-redhat** [comment]
Fixed
