### ISSUE TITLE
Missing performance panels in Volumes dashboard

### ISSUE THREAD

**Issue by fbalak** [Tendrl/monitoring-integration#149]
In [specification for Volumes dashboard](https://github.com/Tendrl/specifications/issues/224) in Row 3 are defined panels:

> Panel 17: IOPS Trend
> 
> - show the IOPS for the volume over a period of time
> - chart type: Line Chart / Spark
> 
> Panel 19: Throughput Trend
> 
> - show throughput for the host over a period of time
> - chart type: Line Chart / Spark

but in [Metrics documentation](https://github.com/Tendrl/documentation/wiki/Metrics) and in the implemented ui is only panel Throughput (IOPS in [Metrics documentation](https://github.com/Tendrl/documentation/wiki/Metrics)):

![227_throughput](https://user-images.githubusercontent.com/22369801/30901699-34ddc17c-a369-11e7-9978-8bf2fbbef1b4.png)

Tested with:
```
tendrl-api-httpd-1.5.2-20170926T110841.a9e16c0.noarch
tendrl-commons-1.5.2-20170926T081245.0fa5e25.noarch
tendrl-api-1.5.2-20170926T110841.a9e16c0.noarch
tendrl-ui-1.5.2-20170926T100141.770936f.noarch
tendrl-node-agent-1.5.2-20170926T090753.09d1818.noarch
tendrl-monitoring-integration-1.5.2-20170926T100202.2e1d15a.noarch
tendrl-grafana-plugins-1.5.2-20170926T100202.2e1d15a.noarch
tendrl-notifier-1.5.2-20170926T102449.7678c47.noarch
```

**Comment by nthomas-redhat** [comment]
Closing the issue as this is not in future roadmap. If its still a requirement let UX drive through a new RFE
