### ISSUE TITLE
Missing Reads and Writes panel in Volumes dashboard

### ISSUE THREAD

**Issue by fbalak** [Tendrl/monitoring-integration#150]
In [specification for Volumes dashboard](https://github.com/Tendrl/specifications/issues/224) in Row 5 is defined panel:

> Panel 26: Reads and Writes by Block Size
> 
> - chart type: Histogram
> - Example:
> - Block Size (x-axis): 1b+ 32b+ 64b+ 128b+ 256b+
> - Read (y-axis): 0 0 0 0 6 Write (y-axis): 908 28 8 5 23

https://github.com/Tendrl/specifications/issues/224#issuecomment-321875857

but in [Metrics documentation](https://github.com/Tendrl/documentation/wiki/Metrics) and in the implemented ui is this panel missing:

![927_readswrites](https://user-images.githubusercontent.com/22369801/30902270-eeece254-a36a-11e7-8467-d95a0504b992.png)

Tested with:
```
tendrl-api-httpd-1.5.2-20170926T110841.a9e16c0.noarch
tendrl-commons-1.5.2-20170926T081245.0fa5e25.noarch
tendrl-api-1.5.2-20170926T110841.a9e16c0.noarch
tendrl-ui-1.5.2-20170926T100141.770936f.noarch
tendrl-node-agent-1.5.2-20170926T090753.09d1818.noarch
tendrl-monitoring-integration-1.5.2-20170926T100202.2e1d15a.noarch
tendrl-grafana-plugins-1.5.2-20170926T100202.2e1d15a.noarch
tendrl-notifier-1.5.2-20170926T102449.7678c47.noarch
```

**Comment by nthomas-redhat** [comment]
Closing the issue as this is not in future roadmap. If its still a requirement let UX drive through a new RFE
