### ISSUE TITLE
Panels in Gluster-at-glance dashboard contain tables instead of graphs

### ISSUE THREAD

**Issue by fbalak** [Tendrl/monitoring-integration#151]
In [specification for Gluster-at-glance dashboard](https://github.com/Tendrl/specifications/issues/222) are following panels defined as graphs:

> **Row 3**
> 
> Panel 17: Top volumes by capacity utilization
> 
> - show the top 5 volumes with the highest disk utilization
> - chart type: Bar Chart / Histogram
> 
> Panel 18: Top bricks by capacity utilization
> 
> - show the top 5 bricks with the highest disk utilization
> - Note: User should be able to discern which host the brick is mounted on
> - chart type: Bar Chart / Histogram
> 
> **Row 4**
> 
> Panel 19: CPU used by Host
> 
> - show CPU utilization for individual hosts within 4 different utilization ranges/buckets: > 90%, 80=90%, 70-80%, and < 70%
> - chart type: Heat Map
> 
> Panel 20: Memory used by Host
> 
> - show memory utilization for individual hosts within 4 different utilization ranges/buckets: > 90%, 80=90%, 70-80%, and < 70%
> - chart type: Heat Map

but in [Metrics documentation](https://github.com/Tendrl/documentation/wiki/Metrics) and in the implemented ui are those panels presented as tables:

![927_graphs](https://user-images.githubusercontent.com/22369801/30905294-af742dda-a374-11e7-9cf5-c7c3bf4995d6.png)

Tested with:
```
tendrl-api-httpd-1.5.2-20170926T110841.a9e16c0.noarch
tendrl-commons-1.5.2-20170926T081245.0fa5e25.noarch
tendrl-api-1.5.2-20170926T110841.a9e16c0.noarch
tendrl-ui-1.5.2-20170926T100141.770936f.noarch
tendrl-node-agent-1.5.2-20170926T090753.09d1818.noarch
tendrl-monitoring-integration-1.5.2-20170926T100202.2e1d15a.noarch
tendrl-grafana-plugins-1.5.2-20170926T100202.2e1d15a.noarch
tendrl-notifier-1.5.2-20170926T102449.7678c47.noarch
```

**Comment by cloudbehl** [comment]
@fbalak We have not shown histograms because the brick name is too large(hostname+brickpath) and that is getting messed up. So due to that, we have come to the solution of not using the histograms.

Please have a look at the attached screenshot.

![screenshot from 2017-11-15 15-03-03](https://user-images.githubusercontent.com/6695156/32828965-ad1a2abc-ca16-11e7-8f34-0dd9af5c4694.png)

**Comment by nthomas-redhat** [comment]
Current design is reviewed and accepted by UX. Any changes in future will be driven by that team. Closing this issue. Open a RFE if any conflicts
