### ISSUE TITLE
2 Throughput panels in Bricks dashboard

### ISSUE THREAD

**Issue by fbalak** [Tendrl/monitoring-integration#152]
There are 2 Throughput panels in Bricks dashboard. I do not see any describtion for Throughput panel in [design document](https://github.com/Tendrl/specifications/issues/230). It seems to me little confusing to have two equally named panels on one dashboard. There are also no values displayed in these panels.

![927_throughput](https://user-images.githubusercontent.com/22369801/30915069-d487b378-a395-11e7-950f-0dde9bd209bf.png)

Tested with:
```
tendrl-api-httpd-1.5.2-20170926T110841.a9e16c0.noarch
tendrl-commons-1.5.2-20170926T081245.0fa5e25.noarch
tendrl-api-1.5.2-20170926T110841.a9e16c0.noarch
tendrl-ui-1.5.2-20170926T100141.770936f.noarch
tendrl-node-agent-1.5.2-20170926T090753.09d1818.noarch
tendrl-monitoring-integration-1.5.2-20170926T100202.2e1d15a.noarch
tendrl-grafana-plugins-1.5.2-20170926T100202.2e1d15a.noarch
tendrl-notifier-1.5.2-20170926T102449.7678c47.noarch
```

**Comment by nthomas-redhat** [comment]
What you see is brick throughput and the underlying physical device throughput

**Comment by rishubhjain** [comment]
@fbalak Can we close this issue?

**Comment by fbalak** [comment]
@rishubhjain ok
