### ISSUE TITLE
Main dashboard says volume down, but volume dashbaord says all is well

### ISSUE THREAD

**Issue by nigelbabu** [Tendrl/monitoring-integration#155]
My cluster had one node down. Now the nodes is back online and functional, but Tendrl seems to think the volume is down on the main dashboard, however, the volume dashboard says all is well. This has since recovered over time by itself. Not sure why it took so long to change status.

**Comment by rishubhjain** [comment]
@cloudbehl We will have to use state instead of status to display Volume Health in grafana volume dashboard, and also modify the mapping
cc: @shtripat

**Comment by rishubhjain** [comment]
@nigelbabu This issue is replicated in
 https://github.com/Tendrl/monitoring-integration/issues/167

**Comment by rishubhjain** [comment]
@nigelbabu Please verify and close the issue
