### ISSUE TITLE
Grafana: Status panels sometimes missing data or say Invalid number

### ISSUE THREAD

**Issue by julienlim** [Tendrl/monitoring-integration#157]
In the Gluster-at-a-glance dashboard, some of the 0 values are not shown (I changed time interval to 2 days) or show as blank. In one case (Bricks), it says "Down - Invalid Number"
![screen shot 2017-10-02 at 3 24 38 pm](https://user-images.githubusercontent.com/5589919/31095244-2e03e838-a786-11e7-942d-19775fd55eeb.png)

@cloudbehl

**Comment by rishubhjain** [comment]
@julienlim We would like to know which tendrl-build is being used. 
If possible please provide tendrl-setup details

**Comment by mbukatov** [comment]
@mbukatov fyi

**Comment by julienlim** [comment]
@rishubhjain I installed using tendrl-ansible on Sept 29 2017.  I'm not sure which build it is.  Is there an easy way to find out which build I'm using?
I'm running this on my vagrant boxes on my laptop.

**Comment by nthomas-redhat** [comment]
This issue is already fixed as part of https://github.com/Tendrl/monitoring-integration/issues/112
fixes are already there is master.
