### ISSUE TITLE
Host Dashboard: Change Memory Free panel to Memory Available panel

### ISSUE THREAD

**Issue by julienlim** [Tendrl/monitoring-integration#164]
The implemented Memory Free panel in Grafana looks correct per design (Tendrl/specifications#223 Panel 10: Memory Free - show memory that is available for the host
chart type: Gauge).

Memory Free calculates with total memory and buff/cache, but it would make more sense to see what memory is really available (without buff/cache).  Right now, memory free looks kind of scary but in fact there is still available 75% of memory.

After reviewing, it would be more usable to change the panel to show Memory Available that includes the following:
total memory available = memory_free + memory_available + shared

Instead of the gauge, showing a total number along with the breakdown of the 4 values that make up the total would be more useful.  If we can show this in a stacked bar chart, that would be great.

![freemem_grafana](https://user-images.githubusercontent.com/5589919/31184624-e9fa57d0-a8f7-11e7-8842-91cced02932b.png)

<img width="576" alt="memory cli" src="https://user-images.githubusercontent.com/5589919/31184675-0aa21e1e-a8f8-11e7-9a94-c9fc28251b46.png">

@cloudbehl @fbalak @mcarrano @Tendrl/tendrl-qe @asrivast@redhat.com

**Comment by mbukatov** [comment]
All these memory related terms are well defined (see `man free`):

```
       total  Total installed memory (MemTotal and SwapTotal in /proc/meminfo)

       used   Used memory (calculated as total - free - buffers - cache)

       free   Unused memory (MemFree and SwapFree in /proc/meminfo)

       shared Memory used (mostly) by tmpfs (Shmem in /proc/meminfo,  available
              on kernels 2.6.32, displayed as zero if not available)

       buffers
              Memory used by kernel buffers (Buffers in /proc/meminfo)

       cache  Memory  used  by  the  page  cache  and slabs (Cached and Slab in
              /proc/meminfo)

       buff/cache
              Sum of buffers and cache

       available
              Estimation of how much  memory  is  available  for  starting  new
              applications,  without  swapping. Unlike the data provided by the
              cache or free fields, this field takes into  account  page  cache
              and  also that not all reclaimable memory slabs will be reclaimed
              due to items being in use (MemAvailable in /proc/meminfo,  avail-
              able  on kernels 3.14, emulated on kernels 2.6.27+, otherwise the
              same as free)
```

This means that:

* if we call something memory free, it should match `MemFree` value in `/proc/meminfo`, which is what `free` reports as free
* while I agree that's not useful to report only memory free value (we don't see how much of memory is buffer or cache), we can't fix that by redefinition of what memory free means

So here it would make more sense to report memory usage, including:

* used
* buffers
* cache
* free

which should add up to total memory available.

Reporting available memory is a bit tricky, as you can see in the description of available value in man page of free above.

**Comment by ltrilety** [comment]
I vote for using `memory_available` nonetheless. I agree it's tricky and it doesn't always shows exact number, but for our need that's quite enough. However the panel name should probably be changed to more proper name like 'Memory Available' to correspond with what command `free` reports. Moreover as @mbukatov points out `memory_free + memory_available + shared` doesn't make sense, just `memory_available` should be enough.

**Comment by cloudbehl** [comment]
@mbukatov @julienlim @ltrilety To my understanding by reading above you want me to change the "Memory Free" panel to "Memory Available" and map it to the free property of memory.

Do you want the percent free(As it is currently) or the number of bytes free?

**Comment by ltrilety** [comment]
@cloudbehl As I see it, you have two options:

1.  Show `used`, `buffers`, `cache` and `free` in some way. E.g. as @julienlim suggested as stacked bar chart. Advantage of this approach is that sum of those numbers gives you total memory.
2. Display `memory_available`. You could also show how big part of it is `free`, but otherwise you cannot show anything as the number doesn't have to sum to total memory with some other available number(s). Even with this disadvantage I prefer this option more because it is easy to read and I think more close to what user wants to know.

I think percentage is fine as long as it shows exact numbers when user hovers over it, or user clicks on that.

**Comment by cloudbehl** [comment]
@ltrilety I see that we don't have memory available as a value directly from collectd plugin. So Will take it as RFE if we want to show the memory available.

Regarding the first approach showing (used, buffers, cache, free)  in the stacked bar chart, We are already showing it in another graph. 
![screenshot from 2017-10-09 12-41-44](https://user-images.githubusercontent.com/6695156/31327966-14c000b8-acf0-11e7-9217-3bde4668aec6.png)

**Comment by ltrilety** [comment]
@cloudbehl well, in that case `available` could be count as `cache` + `free`, not the same as command `free` provides though. It's still better than just showing `free` memory. However I'd like to left final decision on @julienlim or on how majority decides.
@mbukatov, @julienlim what do you think?

**Comment by julienlim** [comment]
@cloudbehl @mbukatov @ltrilety @nthomas-redhat 

Since a lot of the metrics are being shown in the Memory Utilization panel, let's change the Memory Free panel to Memory Panel, and have that be composed of cache + free.  We will need to provide a tooltip to explain this so user will know how the number is derived, though fundamentally, they could probably look at the json or if he/she has edit capabilities be able to look directly at the query.

Instead of showing it as a gauge with %, let's instead show it as a value (singlestat) including a metric, e.g. 14.6 GB.

Thoughts?

**Comment by cloudbehl** [comment]
@julienlim I think the name for the panel can be something like "Memory(Cache+Free). Which will let end user understand at a glance that single stat is composed of Memory cache + Memory free.

@julienlim @nthomas-redhat @ltrilety

**Comment by nthomas-redhat** [comment]
@cloudbehl , tooltip is available(and easy to use) in grafana? if yes let's go with that. Else fall-back on the approach you mentioned.

**Comment by cloudbehl** [comment]
@julienlim @nthomas-redhat I have made the changes it looks like this(image) now.

![screenshot from 2017-10-11 14-51-34](https://user-images.githubusercontent.com/6695156/31432322-f39fed44-ae93-11e7-9573-b5327f73e8c1.png)

**Comment by julienlim** [comment]
@cloudbehl It looks good.  Can we change the panel label from "Memory" to "Memory Available", and have the info tip say: "Memory Available is the sum of memory free and memory cached"?

Thanks!

**Comment by rishubhjain** [comment]
@cloudbehl Please check this issue, If the issue the issue is resolved please close the issue.
cc @julienlim

**Comment by julienlim** [comment]
Verified.
