### ISSUE TITLE
Grafana is using status for volume status but the appropriate value is

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/monitoring-integration#167]
Grafana is using status for volume status but the appropriate value is available in state. So need to map the query to state and update the mappings.

**Comment by nthomas-redhat** [comment]
@cloudbehl , same is applicable for volume status panel on the main dashboard.

![screenshot from 2017-10-06 13-55-43](https://user-images.githubusercontent.com/6671718/31269510-55dc1996-aa9e-11e7-8a52-3e6d85fbc506.png)
