### ISSUE TITLE
Mark bricks of disconnected host as down

### ISSUE THREAD

**Issue by rishubhjain** [Tendrl/monitoring-integration#169]
In reference to https://github.com/Tendrl/monitoring-integration/issues/145, When the host is deleted/detached there is requirement to mark the bricks connected to that particular node as "DOWN"
The ttl seems not be set for bricks and hence bricks doesnt get deleted automatically.

Monitoring-integration recognises the event of host disconnect and hence can mark the disk as "DOWN"

@r0h4n @shtripat Please comment suggestions

**Comment by r0h4n** [comment]
@nnDarshan  @shtripat why do bricks dont have a TTL set?

**Comment by shtripat** [comment]
@r0h4n as per https://github.com/Tendrl/gluster-integration/blob/master/tendrl/gluster_integration/sds_sync/__init__.py#L571 it does have ttl being set. We need to debug once and find why its not set in etcd properly.

**Comment by shtripat** [comment]
@rishubhjain I suspect somehow its due to https://github.com/Tendrl/gluster-integration/blob/master/tendrl/gluster_integration/sds_sync/brick_device_details.py#L77 as its not loading and then setting the fields for the brick while updating the device details. Need to update this piece of code and test once.

**Comment by rishubhjain** [comment]
@r0h4n @shtripat https://github.com/Tendrl/gluster-integration/pull/442 Solves the brick issue, There is a need to mark the brick as down when the host containing the brick is down. but it will have some rep-recursion, for example:, when the node is up again , who will modify the value of brick as up again. I feel there is a need for discussion before implementing the solution.

**Comment by nnDarshan** [comment]
I am not sure, its right to remove the brick(using ttl) if the node goes down. As the brick still exists and we should mark it as down. By removing the brick the number of bricks shown in the dashboards will be wrong. So I feel we should not use ttl for saving bricks and we should explicitly mark the brick status as down when a node goes down
@r0h4n @nthomas-redhat @shtripat @rishubhjain Please provide your inputs

**Comment by rishubhjain** [comment]
@nnDarshan Can we place ttl on brick status and if the node is down and the brick status is deleted then handle it in the same way the node status is handled? (https://github.com/Tendrl/node-agent/commit/f484bacb48a2b65aca70354ed71c66d85767b059)

**Comment by nnDarshan** [comment]
@rishubhjain I was thinking that. We already get to know when node goes down, So feel it will be good to fire a job targeted to any gluster-integration, with the node name, so that it can mark the brick status of all the bricks under that node as down.
Since there will be lots of bricks in the cluster. I feel its inefficient to check if the brick status has vanished just like we do for node status.

**Comment by nthomas-redhat** [comment]
@nnDarshan , I agree with you, correct bricks number should reflect until the node is detached from the cluster . But my question is then how you handle out of band deletes? the ttls introduced basically to handle this. So you need to implement compare and delete during the sync?
@r0h4n ^

**Comment by shtripat** [comment]
@nthomas-redhat out of band deletes would raise events and as handling those events, we would need to delete the entries from etcd. Also if tendrl gets restarted, we might need a master sync one shot to make sure any out of band deletes etc during the period tendrl was down.

@r0h4n @brainfunked suggestions??

**Comment by nthomas-redhat** [comment]
> @nthomas-redhat out of band deletes would raise events and as handling those events, we would need to delete the entries from etcd.

@shtripat , is this taken care now?

**Comment by shtripat** [comment]
>> @shtripat , is this taken care now?

No its not. I am just suggesting a solution here. Need confirmation from @Tendrl/tendrl-core
