### ISSUE TITLE
Add example of options for etcd client-server tls auth into sample config file

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/monitoring-integration#170]
Since [we are planning to use](https://github.com/Tendrl/documentation/wiki/Tendrl-with-a-secure-etcd-cluster) [etcd client-server tls authentication](https://coreos.com/etcd/docs/latest/op-guide/security.html), we need to add commented configuration options for this into sample config file.

## Details

See an example from [node-agent.conf.yaml.sample
](https://github.com/Tendrl/node-agent/blob/master/etc/tendrl/node-agent/node-agent.conf.yaml.sample)

    # Enable etcd SSL TLS cert based auth options
    #etcd_ca_cert_file: /path/to/ca_cert_file.pem
    #etcd_cert_file: /path/to/client_cert_file.pem
    #etcd_key_file: /path/to/client_key_file.pem

But in [monitoring-integration.conf.yaml.sample](https://github.com/Tendrl/monitoring-integration/blob/master/etc/tendrl/monitoring-integration/monitoring-integration.conf.yaml.sample) is see just:

    # Enable etcd username/password based auth, disable if using CA Cert/Client cert based TLS auth options
    #etcd_username: root
    #etcd_password: replace_your_password_here

The expected content should be the same as in case of node agent.

## Reasoning

This change also enables tendrl-ansible to change these values consistently.

**Comment by rishubhjain** [comment]
@mbukatov Please review the patch

**Comment by mbukatov** [comment]
Fixed by https://github.com/Tendrl/monitoring-integration/pull/180
