### ISSUE TITLE
Values not coming on bricks page in grafana

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/monitoring-integration#171]
If there is one volume in a cluster and "All" property is selected in a dropdown in grafana. Then the values are not getting displayed. 

![](https://user-images.githubusercontent.com/5920442/30864222-4ef62022-a2d3-11e7-80fa-4670e6566523.png)

The bug is in grafana, if one value in a drop-down and "All" property is selected then data is not shown.

**Comment by julienlim** [comment]
@cloudbehl I've encountered this same bug.  Is it possible to set the default to go to the first brick in the first node of the first volume?

**Comment by cloudbehl** [comment]
@julienlim Looks like there is some Issue with grafana. This case is only happening when there is 1 volume, If we have more then 1 volume then everything works fine.

**Comment by julienlim** [comment]
If Grafana bug, please release note this.

**Comment by cloudbehl** [comment]
@julienlim Issue is solved with new grafana version.
