### ISSUE TITLE
Brick says it's down when it's not down

### ISSUE THREAD

**Issue by julienlim** [Tendrl/monitoring-integration#174]
On node1:/bricks/brick1 (there's only 1 brick on the node1), and I have create a dummy file that is super large on the brick to get it to > 90% (which is perhaps why it got set to down).  In the grafana dashboard, the status panel is showing the brick as down (when it's not).  I have included gluster volume status, gstatus, screenshots from the Tendrl UI and Grafana host dashboard to show you what I mean.

Note: The capacity percent utilization values differ due to rounding issues.  It should be noted and documented.

Deployed environment: Using master from 5 Oct 2017, deployed using tendrl-ansible on vagrant setup on MacOS laptop.

====

Grafana host dashboard - brick status panel says the brick is down (when it's not):
<img width="1259" alt="screen shot 2017-10-06 at 11 12 38 am" src="https://user-images.githubusercontent.com/5589919/31284936-03cfff34-aa88-11e7-9f9e-cfe612c444af.png">

gluster volume status:
<img width="580" alt="screen shot 2017-10-06 at 11 17 25 am" src="https://user-images.githubusercontent.com/5589919/31285016-2d546340-aa88-11e7-9b81-aea8b3c57cda.png">

<img width="587" alt="screen shot 2017-10-06 at 11 13 57 am" src="https://user-images.githubusercontent.com/5589919/31284967-11e21a58-aa88-11e7-813b-132196c3d15c.png">

gstatus:
<img width="607" alt="screen shot 2017-10-06 at 11 13 20 am" src="https://user-images.githubusercontent.com/5589919/31284963-103f7808-aa88-11e7-94a6-12f5e11db97f.png">

Tendrl UI (Brick tab page):
<img width="1142" alt="screen shot 2017-10-06 at 11 16 46 am" src="https://user-images.githubusercontent.com/5589919/31285037-3ba70e0c-aa88-11e7-97cf-7ad920ec9022.png">

@cloudbehl @Tendrl/tendrl-frontend @Tendrl/tendrl-qe @mcarrano @@rghatvis@redhat.com

**Comment by cloudbehl** [comment]
@rishubhjain @r0h4n @shtripat ^^

**Comment by cloudbehl** [comment]
@julienlim Can you provide setup details to debug?

**Comment by julienlim** [comment]
@cloudbehl I basically used "dd" or "falloc" to create a dummy file on one of the bricks to simulate a  90+% condition on the brick to see how it would show up in the Tendrl UI and Dashboards.

What I noticed was that the threshold did breach, alert was generated, and the utilization was reflected in the various UI's.  However, what I did not expect was that the brick be reported as down (when all that occurred was the utilization was too high).

**Comment by rishubhjain** [comment]
@julienlim Please provide setup details so  that we could debug the issue in detail.

**Comment by cloudbehl** [comment]
@julienlim can you verify this Issue.

**Comment by r0h4n** [comment]
Closing this since not verified beyond a week
