### ISSUE TITLE
Conflicting capacity utilization percentages for the same volume in multiple views

### ISSUE THREAD

**Issue by julienlim** [Tendrl/monitoring-integration#175]
Conflict capacity utilization percentages for the same volume (which only 1 replica set of 3 bricks) in multiple views -- which one should a user trust?  How come they differ in Grafana between the cluster and host dashboards?

Grafana cluster dashboard -- see top 5 utilization for myvolume:
<img width="1137" alt="screen shot 2017-10-06 at 12 02 47 pm" src="https://user-images.githubusercontent.com/5589919/31287229-93ccbc0c-aa8e-11e7-899c-63694f6f643e.png">

Grafana volume dashboard:
<img width="1140" alt="screen shot 2017-10-06 at 12 02 28 pm" src="https://user-images.githubusercontent.com/5589919/31287231-95c3f674-aa8e-11e7-9dd2-2c2897e8a7ff.png">

Tendrl UI bricks view:
<img width="1140" alt="screen shot 2017-10-06 at 12 03 02 pm" src="https://user-images.githubusercontent.com/5589919/31287237-9d2ac334-aa8e-11e7-8cde-9471e1ccd8ec.png">

gstatus --volume output:
<img width="606" alt="screen shot 2017-10-06 at 12 03 12 pm" src="https://user-images.githubusercontent.com/5589919/31287254-a6625eda-aa8e-11e7-88a1-3691ca0fd31d.png">

@cloudbehl @Tendrl/tendrl-frontend @Tendrl/tendrl-qe @mcarrano

**Comment by cloudbehl** [comment]
@julienlim Have Fixed this bug in grafana and opened a Parallel bug in UI for this bug. 

Please verify and close this Issue.

**Comment by rishubhjain** [comment]
@r0h4n @nthomas-redhat Please close the issue.
