### ISSUE TITLE
Monitoring-integration dependency on grafana deletes monitoring integration if grafana is removed

### ISSUE THREAD

**Issue by rishubhjain** [Tendrl/monitoring-integration#18]
Step 1) Install Grafana
Step 2) Install monitoring-integration
Step 3) Remove Grafana [implicitly removes monitoring integation]
Step 4) Install Grafana

Following the above steps leaves monitoring-integration uninstalled on server. We should explicitly mention in the documentation that if grafana is to be reinstalled then monitoring integration will have to be reinstalled.

**Comment by nthomas-redhat** [comment]
I am not this needs to be mentioned explicitly. This is true with any dependencies and admins expected to take care of this.

**Comment by rishubhjain** [comment]
Ok.
