### ISSUE TITLE
Update panel styling to improve readability

### ISSUE THREAD

**Issue by mcarrano** [Tendrl/monitoring-integration#186]
Use of saturated panel background colors to reflect status on current background results in poor overall readability. Recommend updating panel json for all Tendrl dashboards according to the following guidance to improve readability per Grafana panel type.

1- SingleStat panels - use text coloring to reflect state, where applicable, i.e. "Healthy" = green; "Unhealthy = orange"

2- Vonage Status Panels (used for multiple, stacked values) - set 'ColorMode = Metric' to use text rather than background fill to reflect status.

3- Table panels - set 'ColorMode' = Value to use text rather that background fill to reflect status.

The attached screen shot shows how this will look when applied to the Tendrl-Cluster-At-A-Glance dashboard. Note that the background for all panels is light gray.  I have also attached the json of this dashboard for reference.

![screen shot 2017-10-10 at 5 14 39 pm](https://user-images.githubusercontent.com/6619860/31411477-cb9c2e0c-addf-11e7-9239-ffe7ef4c1446.png)

[Tendrl-Gluster-at-a-Glance Copy-1507669380270.txt](https://github.com/Tendrl/monitoring-integration/files/1373485/Tendrl-Gluster-at-a-Glance.Copy-1507669380270.txt)

**Comment by mcarrano** [comment]
@julienlim FYI

**Comment by cloudbehl** [comment]
@mcarrano I think this is a good Idea and Surely it will improve the readability of the dashboard.

We can change the coloring for the single stat and the Vonage Status plugin panel to improve the readability. But in the table panel, we are indicating the status which needs to be visually bold because the number doesn't make much sense in that case. So in case of table panel, we can go with the current pattern.

@mcarrano @julienlim @nthomas-redhat @brainfunked

**Comment by nthomas-redhat** [comment]
@cloudbehl , looks good to me

**Comment by cloudbehl** [comment]
@mcarrano made the changes. Please have a look.
![screenshot from 2017-10-11 14-48-24](https://user-images.githubusercontent.com/6695156/31432144-6c178bac-ae93-11e7-9a27-f94e915671d5.png)

**Comment by julienlim** [comment]
@cloudbehl @mcarrano - looks good.  I'll look forward to seeing these changes in all the dashboards wherever applicable.

**Comment by julienlim** [comment]
@cloudbehl @mcarrano @nthomas-redhat @Tendrl/tendrl-qe 
I just redeployed with tendrl-ansible using master, and the styling updates look good!

<img width="1197" alt="screen shot 2017-10-11 at 1 32 13 pm" src="https://user-images.githubusercontent.com/5589919/31457162-f325cc1c-ae89-11e7-97fc-d5f51d04e676.png">

<img width="1197" alt="screen shot 2017-10-11 at 1 33 51 pm" src="https://user-images.githubusercontent.com/5589919/31457170-faa1c612-ae89-11e7-9baf-23b6e82fbee3.png">

<img width="1135" alt="screen shot 2017-10-11 at 1 40 13 pm" src="https://user-images.githubusercontent.com/5589919/31457173-0061d466-ae8a-11e7-91bf-fc9e7078976b.png">

<img width="1136" alt="screen shot 2017-10-11 at 1 40 24 pm" src="https://user-images.githubusercontent.com/5589919/31457194-08a6db30-ae8a-11e7-9173-34d1bf6cd3e7.png">

**Comment by julienlim** [comment]
@cloudbehl @mcarrano I just made one of my nodes in the cluster go down, and noticed that the Cluster Status changed to red (unhealthy).  It should be orange (unhealthy).

<img width="1205" alt="screen shot 2017-10-11 at 2 42 39 pm" src="https://user-images.githubusercontent.com/5589919/31460232-b02fe69a-ae93-11e7-8ded-5a8e46bbe1e7.png">

This needs to be synchronized with also Tendrl UI.  There's a related bug at https://github.com/Tendrl/ui/issues/673#issuecomment-335870753.

**Comment by mcarrano** [comment]
Looks so much better @cloudbehl Thanks for making these changes.

**Comment by julienlim** [comment]
@cloudbehl Per @mcarrano's investigation, he said regarding the table panels that it did not appear to be possible to apply the text color to the entire row as we had hoped.

So, for now let's leave the tables as currently implemented.

Thank you for the quick turnaround in implementing the singlestat and status panel changes!

**Comment by rishubhjain** [comment]
@julienlim If possible please verify if the issue is still reproducible after the fix. Please update the this issue as per your verification.

**Comment by julienlim** [comment]
Just noting that this "update panel styling to improve readability" bug impacts all the dashboards:

* [Dashboard Spec - Cluster Dashboard](https://github.com/Tendrl/specifications/issues/222)
* [Dashboard Spec - Host Dashboard](https://github.com/Tendrl/specifications/issues/223)
* [Dashboard Spec - Volume Dashboard](https://github.com/Tendrl/specifications/issues/224)
* [Dashboard Spec - Brick Dashboard](https://github.com/Tendrl/specifications/issues/230)
