### ISSUE TITLE
Disk IO Panel - put millisecond (or ms) as part of the y-axis

### ISSUE THREAD

**Issue by julienlim** [Tendrl/monitoring-integration#195]
To be consistent, let's show ms on each of the y-axis units on the Disk IO panel, e.g. 1.0 ms, 1.1 ms, etc.  - like bps/kbps on the Disk Load panel (on left) -- see screenshot.

<img width="1144" alt="screen shot 2017-10-11 at 9 15 08 pm" src="https://user-images.githubusercontent.com/5589919/31474556-8d64c154-aec9-11e7-9f0c-be563a903467.png">

@cloudbehl

**Comment by rishubhjain** [comment]
@julienlim The solution to this issue is submitted by @cloudbehl, Please verify and update the issue.

**Comment by cloudbehl** [comment]
@julienlim please verify.

**Comment by julienlim** [comment]
Fixed and verified.
<img width="379" alt="screen shot 2017-11-03 at 2 02 46 pm" src="https://user-images.githubusercontent.com/5589919/32388993-c9165edc-c09f-11e7-9e24-a6d2b0c8202a.png">
