### ISSUE TITLE
Inode details are not needed in any dashboard.

### ISSUE THREAD

**Issue by nthomas-redhat** [Tendrl/monitoring-integration#201]

**Comment by cloudbehl** [comment]
@nthomas-redhat By Inode details you mean Inode utilization chart and Inode Count, both need to be removed?

**Comment by rishubhjain** [comment]
@nthomas-redhat Any updates on the issue?, Is it required in this build or is it RFE?

**Comment by alokleo** [comment]
There has to be a co-relation between number of files, no of inodes and available capacity. For now, It's OK to leave it as it is i.e.e display the inodes availability.

**Comment by nthomas-redhat** [comment]
Closing the issue as the fix is already merged
