### ISSUE TITLE
Need entity type to differentiate alerts 

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/monitoring-integration#210]
Need entity types like cpu, memory, swap, volume, brick, cluster to differentiate alerts

**Comment by rishubhjain** [comment]
@GowthamShanmugam Please elaborate on the issue, also mention how can I or Ankush help you to solve this issue.

**Comment by GowthamShanmugam** [comment]
It is related to this https://github.com/Tendrl/gluster-integration/issues/449

**Comment by rishubhjain** [comment]
@GowthamShanmugam Any change required from Monitoring-integration side?

**Comment by GowthamShanmugam** [comment]
@rishubhjain this issue is not required, now implementation is different, so i am closing this issue
