### ISSUE TITLE
Some times brick utilization alert dashboard is not created

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/monitoring-integration#214]
After cluster import sometimes brick utilization is not created. After monitoring-integration restart, it is created. It needs to be present after import cluster.

**Comment by GowthamShanmugam** [comment]
@rishubhjain @cloudbehl

**Comment by rishubhjain** [comment]
@GowthamShanmugam Please close this issue

**Comment by GowthamShanmugam** [comment]
This issue is fixed so i am closing this
