### ISSUE TITLE
bad brick names in Grafana

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/monitoring-integration#22]
Part of the brick name should be also hostname the same as when user run `gluster volume info`. Otherwise it could happen, and often will happen, that more bricks have the same name. Because they could be in the same directory on different machines.

Example of Grafana when it happened:
![grafana_brick_name](https://user-images.githubusercontent.com/22369834/29171716-b996a296-7ddd-11e7-8e4f-85c7975e1360.png)

**Comment by nthomas-redhat** [comment]
This bug is not valid anymore. The navigations and the drill downs are modified and bricks are always in the context of hosts. Please have a look at the latest and re-open the issue if you find any discrepancies
