### ISSUE TITLE
Adding the description to the Grafana Panels

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/monitoring-integration#222]
I am planning to add a description to every grafana panel which will be shown as tool-tip to each panel in grafana. This will be helpful to end user about the expectations from each panel.

@julienlim Can you help me provide the description which can be then added to grafana.

**Comment by julienlim** [comment]
@cloudbehl 

Have you looked at the dashboard specs?  I believe there's quite a bit already listed in the spec:
* Cluster dashboard spec: https://github.com/Tendrl/specifications/issues/222
* Host dashboard spec: https://github.com/Tendrl/specifications/issues/223
* Volume dashboard spec: https://github.com/Tendrl/specifications/issues/224
* Brick dashboard spec: https://github.com/Tendrl/specifications/issues/230

I'll start off with some below that should hopefully give you some guidance on the tooltips:
**Cluster dashboard**
* Health panel - The Health panel displays the health of the cluster status, which is either Healthy (green), or Unhealthy (orange).
* Snapshots panel - The Snapshots panel displays the count of active snapshots in the cluster
* Hosts panel - The Hosts panel displays the host status information, including the total number of hosts in the cluster, and the count of hosts based on their respective status.
* Volumes panel - The Volumes panel displays the volume status information, including the total number of volumes in the cluster, and the count of volumes based on their respective status.
... etc. (see specs and Gluster Metrics for further information)

Do have a look and if there are specific panels you need help with tooltip descriptions, do let me know.

I was so hoping we would get tooltips in the release and I'm glad to hear you're planning to add them!

@mcarrano @rghatvis@redhat.com - Please feel free to suggest better wording or any other improvements.

**Comment by cloudbehl** [comment]
@julienlim can we cut short the descriptions? As for a grafana tooltip, it's way too long.

**Comment by julienlim** [comment]
@cloudbehl - what's the length we're talking about?

**Comment by cloudbehl** [comment]
@julienlim I was talking about the description of hosts, Volume and bricks panel. It looks too large for a description to me but as in there are no restrictions from Grafana on a text.

Also, can you provide me with all the description for all the panels with appropriate text? The text in the metrics doc and the specs seem to differ in respect of terminologies. So it would be helpful if you can pass description for all the panels.

**Comment by julienlim** [comment]
@cloudbehl @mcarrano I've created a Google Doc to make it easier to specify the descriptions for the panels.  See 
[Tendrl Grafana Dashboard Panels Descriptions](https://docs.google.com/document/d/11D1Mu4dQHKafSNzATd3aBJUK9q4wnP4jK3cYLDJmbAY/edit?usp=sharing).

**Comment by julienlim** [comment]
@cloudbehl @mcarrano @rghatvis@redhat.com

I've updated [Tendrl Grafana Dashboard Panels Descriptions](https://docs.google.com/document/d/11D1Mu4dQHKafSNzATd3aBJUK9q4wnP4jK3cYLDJmbAY/edit?usp=sharing) for all the dashboards.  I encountered some typos (that I didn't file bugs for but it's mentioned in the document) for some panel labels, one of the metrics shown (lowercase vs. uppercase), some confusing panels that are either duplicate or not clearly specified what they are with their label, e.g. "Utilization" panel.

**Comment by cloudbehl** [comment]
Few of the description is added to grafana and others are pending.

**Comment by julienlim** [comment]
Just noting the document mentioned above provides description for the current dashboards:

* [Dashboard Spec - Cluster Dashboard](https://github.com/Tendrl/specifications/issues/222)
* [Dashboard Spec - Host Dashboard](https://github.com/Tendrl/specifications/issues/223)
* [Dashboard Spec - Volume Dashboard](https://github.com/Tendrl/specifications/issues/224)
* [Dashboard Spec - Brick Dashboard](https://github.com/Tendrl/specifications/issues/230)
