### ISSUE TITLE
Monitoring-integration does not works with latest grafana

### ISSUE THREAD

**Issue by TimothyAsirJeyasing** [Tendrl/monitoring-integration#224]
The latest Grafana package available in the grafana repo is having some sort of plugin or script Issues which blocks our calls. We need to lock down the version for Grafana to 4.5.2.

**Comment by r0h4n** [comment]
@TimothyAsir What exactly are the script issues with latest Grafana package ?

**Comment by TimothyAsirJeyasing** [comment]
@cloudbehl  Could you please describe the issue.

**Comment by julienlim** [comment]
@TimothyAsir @r0h4n @cloudbehl @Tendrl/tendrl-qe I just installed Tendrl with tendrl-ansible from master and am noticing everytime I launch the Dashboard, I get the following plug-in fetching issue:
![screen shot 2017-10-31 at 2 59 36 pm](https://user-images.githubusercontent.com/5589919/32243661-58293a82-be4c-11e7-9ec3-b7ddccb485a2.png)

**Comment by cloudbehl** [comment]
@r0h4n @TimothyAsir @julienlim The issue is with Grafana 4.6.0 version. Its related to loading of the javascript files.

This Issue is being tracked in grafana also: https://github.com/Vonage/Grafana_Status_panel/issues/81

**Comment by dahorak** [comment]
The fix from https://github.com/Tendrl/monitoring-integration/pull/225 is not good, because it breaks any further `yum update` process (you are simply not be able to easily update your system)!

**Comment by r0h4n** [comment]
@TimothyAsir  @cloudbehl Please provide an update regarding 

- Do we see failures using latest Grafana? Are these Tendrl failures or Grafana failures?
- If not above, why cant we move to the latest grafana version?

**Comment by cloudbehl** [comment]
@r0h4n The Issue is with grafana package 4.6.0, it is not related to any tendrl package.
We need to verify the latest release of grafana. i.e 4.6.1, whether the Vonage plugin is working on new package or not
