### ISSUE TITLE
Huge disk space usage by graphite with big no of volumes

### ISSUE THREAD

**Issue by shtripat** [Tendrl/monitoring-integration#228]
During verification with huge no of volumes (~100) we have seen that graphite consumes almost 40GB disk space for maintaining .wsp files for the cluster in a ~24hrs timeframe.
We need to look at if there are some duplicate .wsp files and remove any unused ones .

**Comment by cloudbehl** [comment]
linking: https://github.com/Tendrl/monitoring-integration/issues/261

**Comment by nthomas-redhat** [comment]
Also there is https://github.com/Tendrl/monitoring-integration/issues/265 as well. Since the other issues are already in place, closing this issue
