### ISSUE TITLE
Tendrl cluster id does not match Grafana cluster id

### ISSUE THREAD

**Issue by Daniel-Pivonka** [Tendrl/monitoring-integration#25]
![tendrl_id](https://user-images.githubusercontent.com/22037319/29176388-bd23156c-7db9-11e7-9eea-b345686eeaf3.png)
![grafana_id](https://user-images.githubusercontent.com/22037319/29176389-bd339de2-7db9-11e7-9ef9-52fc292bb285.png)

The cluster id displayed in tendrl does not match the cluster id displayed in grafana

**Comment by julienlim** [comment]
@Tendrl/qe @Tendrl/tendrl-core @japplewhite jjkabrown1 @Daniel-Pivonka 

Per looking at the Milestone 1  (Aug 4 2017) build, after installed, we looked the cluster ID shown in Grafana/Graphite vs. what we see in the Tendrl UI (based on etcd) for the Gluster cluster being monitored, and they differ in what is displayed.  The nodes (server1 and server2) that are in the cluster correct.

Another oddity observed:
* Per @Daniel-Pivonka, the storage free says 53.7 GB, when there are only 2 drives (with total capacity of 40 GB and 8 GB).

**Comment by cloudbehl** [comment]
@Daniel-Pivonka please verify the Issue if it's still reproducible. Otherwise, close the Issue.

**Comment by julienlim** [comment]
@cloudbehl Daniel Pivonka (was interning) and will not be able to reproduce to verify the issue. 

I think @Tendrl/tendrl-qe should verify the data as part of their testing, and only upon verification should this issue be closed.

**Comment by mbukatov** [comment]
@julienlim ack, I have created a tracker issue for us to come up with some test cases for this

**Comment by nthomas-redhat** [comment]
This issue verified. Please re-open if you find it otherwise
