### ISSUE TITLE
Bricks dashboard: 2 Throughput panels with differing output

### ISSUE THREAD

**Issue by julienlim** [Tendrl/monitoring-integration#251]
In the Tendrl 1.5.4 release, the bricks dashboard has 2 panels for Throughput with differing output.

It's unclear what the difference is at first glance.  Either one of them needs a different label, or we should only have 1 of them.  It would be also good to describe what they are.

![screen shot 2017-11-09 at 3 58 46 pm](https://user-images.githubusercontent.com/5589919/32629450-3cefaf18-c567-11e7-87a8-957f9901e9f2.png)

@cloudbehl @Tendrl/tendrl-qe @nthomas-redhat @mcarrano

**Comment by shtripat** [comment]
@brainfunked @nthomas-redhat comments?

**Comment by nthomas-redhat** [comment]
@julienlim , what changes to the label you suggest here?

**Comment by julienlim** [comment]
Related Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1511687

From looking at [monitoring-integration/etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json](https://github.com/Tendrl/monitoring-integration/blob/daee676541b31598a9f575aff37942f3b7179ba8/etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json), here is what I saw:

(1) the first Throughput panel is showing the sum of Brick IOPS (read + write) for the brick path
tendrl.clusters.$cluster_id.volumes.$volume_name.nodes.$host_name.bricks.$brick_path.iops.gauge-read + tendrl.clusters.$cluster_id.volumes.$volume_name.nodes.$host_name.bricks.$brick_path.iops.gauge-write
Current Description: N/A

(2) the second Throughput panel is showing disk read and disk write based on tendrl.clusters.$cluster_id.volumes.$volume_name.nodes.$host_name.bricks.$brick_path.device.*.disk_octets.read and tendrl.clusters.$cluster_id.volumes.$volume_name.nodes.$host_name.bricks.$brick_path.device.*.disk_octets.write.
Current Description: "The Throughput panel displays brick-level read and write operations fetched using “gluster volume profile”

@nthomas-redhat 
Perhaps calling the first Throughput panel what it's showing i.e. "IOPS" with a description of "The IOPS panel displays the sum of IOPS (read + write) for a given brick path".

Thoughts?  Also do we actually collect brick path IOPS data?  I've not yet seen this data yet.  If no, then we probably should not show it.  Can someone verify please?

@brainfunked @cloudbehl @nthomas-redhat @Tendrl/tendrl-core @Tendrl/tendrl-qe @mcarrano

**Comment by julienlim** [comment]
Can IOPS for the volume be derived from the bricks IOPS (if we're capturing it above)?  This is raised in https://bugzilla.redhat.com/show_bug.cgi?id=1514054 (missing Volume IOPS panel).

@brainfunked @cloudbehl @nthomas-redhat @Tendrl/tendrl-core @Tendrl/tendrl-qe @mcarrano

**Comment by nthomas-redhat** [comment]
> @nthomas-redhat
> Perhaps calling the first Throughput panel what it's showing i.e. "IOPS" with a description of "The IOPS panel displays the sum of IOPS (read + write) for a given brick path".
> 
> Thoughts? Also do we actually collect brick path IOPS data? I've not yet seen this data yet. If no, then we probably should not show it. Can someone verify please?

Yes we collect that.
Ack, we will make the label changes accordingly

**Comment by julienlim** [comment]
@nthomas-redhat @cloudbehl Please change labels as well as descriptions (so it will be clear to user what it's about).  Thanks.

**Comment by nthomas-redhat** [comment]
Fixed. Closing the issue
