### ISSUE TITLE
Bricks dashboard: Unclear what "Utilization" panel is showing

### ISSUE THREAD

**Issue by julienlim** [Tendrl/monitoring-integration#252]
There's a panel called "Utilization" (Bottom right corner) and it's unclear to the user what this is metric is showing.  Is the the disk device capacity utilization or something else?  Please make the label clearer as to what this utilization is about.

![screen shot 2017-11-09 at 3 58 46 pm](https://user-images.githubusercontent.com/5589919/32631281-b9170d24-c56d-11e7-8733-4f35628edc73.png)

@cloudbehl @Tendrl/tendrl-qe @mcarrano

**Comment by julienlim** [comment]
@cloudbehl It would be good to include description for this panel as mentioned in https://github.com/Tendrl/monitoring-integration/issues/222.  I've updated all the descriptions for all the dashboard panels based on what's currently implemented as best as I could figure out -- see https://docs.google.com/document/d/11D1Mu4dQHKafSNzATd3aBJUK9q4wnP4jK3cYLDJmbAY/edit?usp=sharing.

**Comment by shtripat** [comment]
@brainfunked @nthomas-redhat comments?

**Comment by ltrilety** [comment]
BTW I'd like to know that too, as I used all bricks disks and the disk load utilization still shows 0.

**Comment by r0h4n** [comment]
Fixed: https://github.com/Tendrl/monitoring-integration/pull/264

Please verify @ltrilety

**Comment by julienlim** [comment]
From looking at https://github.com/Tendrl/monitoring-integration/pull/264, it's mount point utilization for the brick.

**Comment by cloudbehl** [comment]
@julienlim yes it's mount point utilization for a brick

**Comment by julienlim** [comment]
@cloudbehl Are we going to change the label for the chart to "Mount Point Utilization" and update Description accordingly?

**Comment by cloudbehl** [comment]
@julienlim can you provide a description of the Mount Point Utilization panel.

Sorry, If you have already provided I am not able to find it. Thanks

**Comment by julienlim** [comment]
@cloudbehl 

Label: Mount Point Utilization
Description: Mount Point Utilization for a given brick over a period of time.

**Comment by nthomas-redhat** [comment]
Fixed, closing the issue
