### ISSUE TITLE
Alert list view on Grafana should display a message when no alerts are present

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/monitoring-integration#256]
Currently no message is being displayed on the alert list page, when no alert is present is the Grafana.

![empty-alert-list](https://user-images.githubusercontent.com/5517376/32719791-898ec4a8-c887-11e7-81f2-f59d5106a046.png)

**Comment by GowthamShanmugam** [comment]
I think we can configure this, @cloudbehl is that possible to fix this?

**Comment by nthomas-redhat** [comment]
This is not relevant to what we are supporting. closing the issue
