### ISSUE TITLE
If two clusters imported in tendrl, the georep session details are not correct in grafana dashboard

### ISSUE THREAD

**Issue by shtripat** [Tendrl/monitoring-integration#257]
Created two gluster clusters. In one of the clusters, setup a georep session between volumes.
Imported both the clusters in tendrl.

In grafana cluster dahsboard (at a glance), both the clusters show a georep session available and up, whereas there is only one cluster which has georep setup. At volume level dashboards, the details are correct and are shown only for volume which has georep setup.

**Comment by GowthamShanmugam** [comment]
@shtripat is this issue is fixed? if yes please close this

**Comment by shtripat** [comment]
This is fixed. Closing now.
