### ISSUE TITLE
Monitoring-integration process the create volume job before all  gluster sync collect all details of bricks

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/monitoring-integration#260]
When the volume is created on the command line, gluster event will pass the volume create an event to the gluster-integration socket, Gluster-integration is creating a job for volume creation dashbaord. Monitoring-integration is processing a job before gluster sync collects the brick details from corresponding storage nodes.

**Comment by r0h4n** [comment]
So we want to ensure monitoring integration keeps checking for any new clusters or objects in clusters and create the dashboards and panels as required. 

This will enable us to move away from the current way where we create dashboard and panels only once after import or if there's any new objects in the cluster
