### ISSUE TITLE
 No module named cliutils.cliutils 

### ISSUE THREAD

**Issue by SaravanaStorageNetwork** [Tendrl/monitoring-integration#266]
I was facing error during tendrl-monitoring-integration service start..

Refer below log:

> [root@localhost site-packages]# /bin/tendrl-monitoring-integration
> Creating namespace.monitoring from source tendrl.monitoring_integrationnamespace.monitoring created!Finding objects in namespace.monitoring.objectsRegistering object namespace.monitoring.objects.AlertTypesFinding atoms in namespace.monitoring.objects.AlertTypes.atomsFinding flows in namespace.monitoring.objects.AlertTypes.flowsRegistering object namespace.monitoring.objects.ConfigFinding atoms in namespace.monitoring.objects.Config.atomsFinding flows in namespace.monitoring.objects.Config.flowsRegistering object namespace.monitoring.objects.DefinitionFinding atoms in namespace.monitoring.objects.Definition.atomsFinding flows in namespace.monitoring.objects.Definition.flowsRegistering object namespace.monitoring.objects.TriggerFinding atoms in namespace.monitoring.objects.Trigger.atomsFinding flows in namespace.monitoring.objects.Trigger.flowsFinding flows in namespace.monitoring.flowsRegistering flow namespace.monitoring.flows.DeleteResourceFromGraphiteRegistering flow namespace.monitoring.flows.NewClusterDashboardRegistering flow namespace.monitoring.flows.UpdateDashboardRegistering flow namespace.monitoring.flows.UpdateDashboardSetup Tendrl definitions (.yml)for namespace.monitoringValidating registered (.py) flows in namespace.monitoring.flowsValidating defined (.yml) flows in namespace.monitoring.flowsValidating registered (.py) objects in namespace.monitoring.objectsValidating defined (.yml) objects in namespace.monitoring.objectsSetup Config for namespace.monitoringSetup central store clients for namespace.monitoringCreating namespace.tendrl from source tendrl.commonsnamespace.tendrl created!Finding objects in namespace.tendrl.objectsRegistering object namespace.tendrl.objects.AlertFinding atoms in namespace.tendrl.objects.Alert.atomsFinding flows in namespace.tendrl.objects.Alert.flowsRegistering object namespace.tendrl.objects.BlockDeviceFinding atoms in namespace.tendrl.objects.BlockDevice.atomsFinding flows in namespace.tendrl.objects.BlockDevice.flowsRegistering object namespace.tendrl.objects.ClusterFinding atoms in namespace.tendrl.objects.Cluster.atomsRegistering atom namespace.tendrl.objects.Cluster.atoms.CheckClusterAvailableRegistering atom namespace.tendrl.objects.Cluster.atoms.ConfigureMonitoringRegistering atom namespace.tendrl.objects.Cluster.atoms.CreateRegistering atom namespace.tendrl.objects.Cluster.atoms.ImportClusterRegistering atom namespace.tendrl.objects.Cluster.atoms.ImportCreatedClusterRegistering atom namespace.tendrl.objects.Cluster.atoms.PersistClusterDetailsAfterCreateRegistering atom namespace.tendrl.objects.Cluster.atoms.ValidCreateClusterParamsRegistering atom namespace.tendrl.objects.Cluster.atoms.ValidImportClusterParamsFinding flows in namespace.tendrl.objects.Cluster.flowsRegistering object namespace.tendrl.objects.AlertFinding atoms in namespace.tendrl.objects.Alert.atomsFinding flows in namespace.tendrl.objects.Alert.flowsRegistering object namespace.tendrl.objects.ClusterAlertFinding atoms in namespace.tendrl.objects.ClusterAlert.atomsFinding flows in namespace.tendrl.objects.ClusterAlert.flowsRegistering object namespace.tendrl.objects.ClusterAlertCountersFinding atoms in namespace.tendrl.objects.ClusterAlertCounters.atomsFinding flows in namespace.tendrl.objects.ClusterAlertCounters.flowsRegistering object namespace.tendrl.objects.ClusterNodeContextFinding atoms in namespace.tendrl.objects.ClusterNodeContext.atomsFinding flows in namespace.tendrl.objects.ClusterNodeContext.flowsRegistering object namespace.tendrl.objects.ClusterTendrlContextFinding atoms in namespace.tendrl.objects.ClusterTendrlContext.atomsFinding flows in namespace.tendrl.objects.ClusterTendrlContext.flowsRegistering object namespace.tendrl.objects.CpuFinding atoms in namespace.tendrl.objects.Cpu.atomsFinding flows in namespace.tendrl.objects.Cpu.flowsRegistering object namespace.tendrl.objects.DefinitionFinding atoms in namespace.tendrl.objects.Definition.atomsFinding flows in namespace.tendrl.objects.Definition.flowsRegistering object namespace.tendrl.objects.DetectedClusterFinding atoms in namespace.tendrl.objects.DetectedCluster.atomsFinding flows in namespace.tendrl.objects.DetectedCluster.flowsRegistering object namespace.tendrl.objects.DiskFinding atoms in namespace.tendrl.objects.Disk.atomsFinding flows in namespace.tendrl.objects.Disk.flowsRegistering object namespace.tendrl.objects.JobFinding atoms in namespace.tendrl.objects.Job.atomsFinding flows in namespace.tendrl.objects.Job.flowsRegistering object namespace.tendrl.objects.MemoryFinding atoms in namespace.tendrl.objects.Memory.atomsFinding flows in namespace.tendrl.objects.Memory.flowsRegistering object namespace.tendrl.objects.NodeFinding atoms in namespace.tendrl.objects.Node.atomsRegistering atom namespace.tendrl.objects.Node.atoms.BaseAtomRegistering atom namespace.tendrl.objects.Node.atoms.CheckNodeUpRegistering atom namespace.tendrl.objects.Node.atoms.BaseAtomRegistering atom namespace.tendrl.objects.Node.atoms.CmdRegistering atom namespace.tendrl.objects.Node.atoms.IsNodeTendrlManagedFinding flows in namespace.tendrl.objects.Node.flowsRegistering object namespace.tendrl.objects.AlertFinding atoms in namespace.tendrl.objects.Alert.atomsFinding flows in namespace.tendrl.objects.Alert.flowsRegistering object namespace.tendrl.objects.NodeAlertFinding atoms in namespace.tendrl.objects.NodeAlert.atomsFinding flows in namespace.tendrl.objects.NodeAlert.flowsRegistering object namespace.tendrl.objects.NodeAlertCountersFinding atoms in namespace.tendrl.objects.NodeAlertCounters.atomsFinding flows in namespace.tendrl.objects.NodeAlertCounters.flowsRegistering object namespace.tendrl.objects.NodeContextFinding atoms in namespace.tendrl.objects.NodeContext.atomsFinding flows in namespace.tendrl.objects.NodeContext.flowsRegistering object namespace.tendrl.objects.NodeNetworkFinding atoms in namespace.tendrl.objects.NodeNetwork.atomsFinding flows in namespace.tendrl.objects.NodeNetwork.flowsRegistering object namespace.tendrl.objects.AlertFinding atoms in namespace.tendrl.objects.Alert.atomsFinding flows in namespace.tendrl.objects.Alert.flowsRegistering object namespace.tendrl.objects.NotificationOnlyAlertFinding atoms in namespace.tendrl.objects.NotificationOnlyAlert.atomsFinding flows in namespace.tendrl.objects.NotificationOnlyAlert.flowsRegistering object namespace.tendrl.objects.OsFinding atoms in namespace.tendrl.objects.Os.atomsFinding flows in namespace.tendrl.objects.Os.flowsRegistering object namespace.tendrl.objects.PlatformFinding atoms in namespace.tendrl.objects.Platform.atomsFinding flows in namespace.tendrl.objects.Platform.flowsRegistering object namespace.tendrl.objects.ServiceFinding atoms in namespace.tendrl.objects.Service.atomsRegistering atom namespace.tendrl.objects.Service.atoms.BaseAtomRegistering atom namespace.tendrl.objects.Service.atoms.CheckServiceStatusFinding flows in namespace.tendrl.objects.Service.flowsRegistering object namespace.tendrl.objects.TendrlContextFinding atoms in namespace.tendrl.objects.TendrlContext.atomsFinding flows in namespace.tendrl.objects.TendrlContext.flowsRegistering object namespace.tendrl.objects.DiskFinding atoms in namespace.tendrl.objects.Disk.atomsFinding flows in namespace.tendrl.objects.Disk.flowsRegistering object namespace.tendrl.objects.VirtualDiskFinding atoms in namespace.tendrl.objects.VirtualDisk.atomsFinding flows in namespace.tendrl.objects.VirtualDisk.flowsFinding flows in namespace.tendrl.flowsRegistering flow namespace.tendrl.flows.AuthorizeSshKeyRegistering flow namespace.tendrl.flows.ConfigureMonitoringRegistering flow namespace.tendrl.flows.CreateClusterRegistering flow namespace.tendrl.flows.ExpandClusterRegistering flow namespace.tendrl.flows.ImportClusterRegistering flow namespace.tendrl.flows.SetupSshSetup Tendrl definitions (.yml)for namespace.tendrlValidating registered (.py) flows in namespace.tendrl.flowsValidating defined (.yml) flows in namespace.tendrl.flowsValidating registered (.py) objects in namespace.tendrl.objectsValidating defined (.yml) objects in namespace.tendrl.objectsSetup NodeContext for namespace.tendrlLoad definitions (.yml) for namespace.tendrl.objects.NodeContextLoad definitions (.yml) for namespace.tendrl.objects.TendrlContextTraceback (most recent call last):
>   File "/bin/tendrl-monitoring-integration", line 9, in <module>
>     load_entry_point('tendrl-monitoring-integration==1.5.4', 'console_scripts', 'tendrl-monitoring-integration')()
>   File "/usr/lib/python2.7/site-packages/tendrl/monitoring_integration/manager/__init__.py", line 177, in main
>     monitoring_integration_manager = MonitoringIntegrationManager()
>   File "/usr/lib/python2.7/site-packages/tendrl/monitoring_integration/manager/__init__.py", line 40, in __init__
>     self.webhook_receiver = webhook_receiver.WebhookReceiver()
>   File "/usr/lib/python2.7/site-packages/tendrl/monitoring_integration/grafana/webhook_receiver.py", line 20, in __init__
>     self.alert_handler = AlertHandlerManager()
>   File "/usr/lib/python2.7/site-packages/tendrl/monitoring_integration/alert/handlers/__init__.py", line 94, in __init__
>     self._load_handlers()
>   File "/usr/lib/python2.7/site-packages/tendrl/monitoring_integration/alert/handlers/__init__.py", line 73, in _load_handlers
>     mod = importlib.import_module(handler_fqdn)
>   File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
> ImportError: No module named cliutils.cliutils
>

**Comment by r0h4n** [comment]
Are you using tendrl-ansible to install Tendrl? Please try to reproduce the issue on a deployment done using tendrl-ansible

tendrl-ansible: https://github.com/Tendrl/tendrl-ansible

**Comment by SaravanaStorageNetwork** [comment]
We(gluster-kubernetes) are planning to write a Dockerfile for running tendrl server in container, hence manual steps should work too. 

@r0h4n Could you help in filling the gaps in manual steps?  
I can provide the logs necessary
