### ISSUE TITLE
Tables in Gluster at a Glance are exceeding the table border

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/monitoring-integration#268]
![1114_tables](https://user-images.githubusercontent.com/6695156/32851718-cda614cc-ca5b-11e7-9176-7e9f80aec4e9.png)
![screenshot from 2017-11-15 23-24-39](https://user-images.githubusercontent.com/6695156/32851925-715a49da-ca5c-11e7-9e2e-865c5a977473.png)

**Comment by cloudbehl** [comment]
@julienlim can you suggest something to overcome this Issue. I have tried giving more space to these panels(please check the below image). Does it look ok or do you have anything else in mind?

![screenshot from 2017-11-15 23-29-15](https://user-images.githubusercontent.com/6695156/32852084-ede8431c-ca5c-11e7-8247-f5e64aef421a.png)

**Comment by julienlim** [comment]
Noting that it appears the reason for the issue appears to be very long host names which are wordwrapping causing the scrolling to occur.  This problem still persists with the different visualization, e.g. bar charts (https://github.com/Tendrl/monitoring-integration/issues/151).

**Comment by julienlim** [comment]
@cloudbehl Some suggestions is to try turning the non-top 5 panels into trend utilization charts.  For top 5 panels, stretch them wider?  Do you want to try that?
