### ISSUE TITLE
Same volume names across multiple clusters mess up the brick info shown on the dashboard

### ISSUE THREAD

**Issue by nthomas-redhat** [Tendrl/monitoring-integration#318]
If you create volumes with same names across multiple clusters, dashboard shows brick numbers as sum of the brick numbers of volumes across multiple clusters.

**Comment by cloudbehl** [comment]
@GowthamShanmugam Is this Issue fixed? can you please check.

**Comment by GowthamShanmugam** [comment]
This issue is fixed in part of refactoring patch

**Comment by GowthamShanmugam** [comment]
We can close this issue @cloudbehl
