### ISSUE TITLE
README file is missing configuration step: specify etcd_connection

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/monitoring-integration#34]
The readme file doesn't mention configuration of `etcd_connection` in `/etc/tendrl/monitoring-integration/monitoring-integration.conf.yaml` file.

**Comment by rishubhjain** [comment]
@mbukatov I guess now the instructions in readme are not used to install Monitoring-Integration, I will update readme but I guess this issue can be closed

**Comment by mbukatov** [comment]
@rishubhjain When I open the readme file, I still see the installation instructions there. And while you are right that the main description of Tendrl installation is placed elsewhere (tendrl wiki), I don't think it's good practice to keep broken installation instructions in the readme file.

We have 2 options, either update the instructions in the readme, or just remove the instructions from the readme file completely (if you think that there is no point in keeping 2 places updated).

**Comment by rishubhjain** [comment]
@mbukatov I will provide a link to the tendrl wiki in the readme file of Monitoring-integration

**Comment by nthomas-redhat** [comment]
@mbukatov , is this a valid issue or fixed?

**Comment by rishubhjain** [comment]
@mbukatov Changes are done as per requirement. Please verify and close the issue

**Comment by mbukatov** [comment]
ok
