### ISSUE TITLE
We need to remove the hard-coding of dashboard names from code

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/monitoring-integration#350]
https://github.com/Tendrl/monitoring-integration/blob/583e76f91bc644710ce953a6566adc5654f8e0d8/tendrl/monitoring_integration/grafana/alert_utils.py#L16

**Comment by cloudbehl** [comment]
https://github.com/Tendrl/monitoring-integration/blob/583e76f91bc644710ce953a6566adc5654f8e0d8/tendrl/monitoring_integration/grafana/alert_utils.py#L18

https://github.com/Tendrl/monitoring-integration/blob/583e76f91bc644710ce953a6566adc5654f8e0d8/tendrl/monitoring_integration/grafana/alert_utils.py#L41

**Comment by cloudbehl** [comment]
@GowthamShanmugam ^^

**Comment by GowthamShanmugam** [comment]
Need to be fixed in next release

**Comment by cloudbehl** [comment]
@GowthamShanmugam This bug is fixed as part of name changes of dashboard.

**Comment by GowthamShanmugam** [comment]
@cloudbehl Yes
