### ISSUE TITLE
Exception in logs

### ISSUE THREAD

**Issue by nthomas-redhat** [Tendrl/monitoring-integration#370]
Mar  7 21:47:16 server tendrl-monitoring-integration: Exception in thread Thread-600:
Mar  7 21:47:16 server tendrl-monitoring-integration: Traceback (most recent call last):
Mar  7 21:47:16 server tendrl-monitoring-integration: File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
Mar  7 21:47:16 server tendrl-monitoring-integration: self.run()
Mar  7 21:47:16 server tendrl-monitoring-integration: File "/usr/lib64/python2.7/threading.py", line 765, in run
Mar  7 21:47:16 server tendrl-monitoring-integration: self.__target(*self.__args, **self.__kwargs)
Mar  7 21:47:16 server tendrl-monitoring-integration: File "/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py", line 148, in process_job
Mar  7 21:47:16 server tendrl-monitoring-integration: if job.payload["type"] == NS.type and \
Mar  7 21:47:16 server tendrl-monitoring-integration: TypeError: 'NoneType' object has no attribute '__getitem__'
Mar  7 21:47:18 server journal: 2018-03-07 16:17:18.387220+00:00 - node_agent - /usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py:169 - process_job - INFO - Node (47ad31f3-ff99-4b0f-b3ca-af576facfaeb)(type: node)(tags: ['tendrl/central-store', u'tendrl/integration/monitoring', 'tendrl/monitor', 'tendrl/node', u'tendrl/node_47ad31f3-ff99-4b0f-b3ca-af576facfaeb', 'tendrl/server']) will not process job-a0ad61aa-d47c-4466-935f-2563cdda6722 (tags: tendrl/node_6dc80590-78f9-4df1-8da1-22e0a07f860b)

**Comment by GowthamShanmugam** [comment]
@nthomas-redhat I am not seen this exception in latest master

**Comment by nthomas-redhat** [comment]
thanks, I am closing the issue
