### ISSUE TITLE
hosts alerts number

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/monitoring-integration#374]
API `nodes` call is not always returning number of alerts per node, only when some alert happens for the node. That leads to situation when UI says `No Data`. Which is correct from UI perspective because there really are no data. However as monitoring software we are aware how many alerts we got. So proper behaviour for API will be to report 0 alerts in the case when no alert comes at all.

Tendrl version:
tendrl-api-1.6.1-1.el7.centos.noarch

**Comment by r0h4n** [comment]
@GowthamShanmugam 

As @shirshendu  suggested, we need default (0) values for all alert counter objects
-
 https://github.com/Tendrl/commons/blob/master/tendrl/commons/objects/cluster_node_alert_counters/__init__.py
- https://github.com/Tendrl/commons/blob/master/tendrl/commons/objects/node_alert_counters/__init__.py
- https://github.com/Tendrl/commons/blob/master/tendrl/commons/objects/cluster_alert_counters/__init__.py
- https://github.com/Tendrl/node-agent/blob/master/tendrl/integrations/gluster/objects/volume_alert_counters/__init__.py

**Comment by GowthamShanmugam** [comment]
@r0h4n but already it default value is 0 only 
https://github.com/Tendrl/commons/blob/master/tendrl/commons/objects/node_alert_counters/__init__.py#L7

**Comment by r0h4n** [comment]
@Tendrl/api @Tendrl/frontend  Backend sets alert counter value to 0 as default. Could you guys check if tendrl/api or tendrl/ui correctly displays the default value (0) if no alerts found?

**Comment by shirshendu** [comment]
![image](https://user-images.githubusercontent.com/1880361/37391376-005021dc-2791-11e8-925c-bef197350fe8.png)
We have `"warning_count": "0"` in the API. @Tendrl/frontend ?

**Comment by gnehapk** [comment]
@r0h4n @shirshendu As per @mcarrano [comment ](https://github.com/Tendrl/ui/issues/658#issuecomment-334172813), UI displays `0`, if `warning_count` is `0` in API response else `No Data` in case no data is available for alert.

**Comment by ltrilety** [comment]
My scenario is very simple, just import the cluster and go to the cluster details - Hosts page.

![image](https://user-images.githubusercontent.com/22369834/37462489-629a2470-2852-11e8-84c0-85c582102a01.png)

![image](https://user-images.githubusercontent.com/22369834/37462451-43bbe20a-2852-11e8-8daa-2d0c485e2647.png)

**Comment by r0h4n** [comment]
@GowthamShanmugam Please triage this, you have fixed this issue recently

**Comment by GowthamShanmugam** [comment]
@shirshendu only for cluster and volume only Api is returning alert, for nodes alert count api is not returning anything.

**Comment by GowthamShanmugam** [comment]
This issue is fixed, please verify and close this issue @ltrilety

**Comment by nthomas-redhat** [comment]
@ltrilety ,Closing the issue. If you find any discrepancies, please re-open the issue

**Comment by ltrilety** [comment]
Checked on:
tendrl-ui-1.6.1-3.el7rhgs.noarch

looks good
