### ISSUE TITLE
Is it necessary to take graphite data as archive when any resource is deleted

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/monitoring-integration#402]
I feel there is no meaning to take an archive of graphite data when volume or brick or node is deleted. is it really required? and it won't be deleted forever. this will reduce the performance.

**Comment by GowthamShanmugam** [comment]
@shtripat @nthomas-redhat @r0h4n @cloudbehl

**Comment by cloudbehl** [comment]
@GowthamShanmugam I agree there is no use of it. We can simply remove that data without archiving it
