### ISSUE TITLE
Top 5 bricks by utilization fails if all bricks have same name

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/monitoring-integration#44]
Seems like volume name needs to prefixed to the brick names to ensure they are uniquely listed in "Top 5 bricks by utilization"

**Comment by cloudbehl** [comment]
@r0h4n @nthomas-redhat The best possible for the brick name with host name is "dhcp43-116_lab_eng_blr_redhat_com.bricks.|root|gluster_bricks|master_b2". Bricks word is coming in between, Is it good?

**Comment by cloudbehl** [comment]
@r0h4n the Issue is fixed please close.
