### ISSUE TITLE
Grafana alert dashboard does not raise alerts when nodes have string "tendrl" in hostname

### ISSUE THREAD

**Issue by anmolsachan** [Tendrl/monitoring-integration#480]
Alerts do not show in alerts dashboard. Eg for brick Dashboard.
Also metrics column does not appear properly. Refer images.

![screenshot from 2018-06-04 17-52-48](https://user-images.githubusercontent.com/8753636/40917909-759a5918-6822-11e8-95be-5bb9104426a9.png)
![screenshot from 2018-06-04 17-54-39](https://user-images.githubusercontent.com/8753636/40917911-75d018fa-6822-11e8-8225-fd044280d466.png)

**Comment by r0h4n** [comment]
Need more information, please elaborate on the issue

**Comment by anmolsachan** [comment]
@r0h4n I have attached the images, to understand the issue correctly.

**Comment by GowthamShanmugam** [comment]
please close this issue if it is fixed
