### ISSUE TITLE
Running grafana using custom configuration file

### ISSUE THREAD

**Issue by rishubhjain** [Tendrl/monitoring-integration#60]
Presently Monitoring-integration replaces grafana.ini file with customized grafana.ini file, which is not a right approach.

Monitoring-integration must not replace the original grafana.ini file, instead should pass the path to custom setting file as parameter when grafana service is started.

**Comment by rishubhjain** [comment]
@brainfunked We will have to mention the path to the customized configuration file(grafana.ini) in /etc/sysconfig/grafana-server where path of all the configuration files used by grafana is listed.
This can be done by monitoring-integration.

**Comment by TimothyAsirJeyasing** [comment]
@rishubhjain Hope we can have our custom configuration as a separate file. So that we need not to modify the default one which comes with Grafana. How about using Custom configuration from $WORKING_DIR/conf/custom.ini
