### ISSUE TITLE
Monitoring-integration service fails if grafana server is not running

### ISSUE THREAD

**Issue by rishubhjain** [Tendrl/monitoring-integration#61]
Monitoring-integration service dependencies must be mentioned in tendrl-monitoring-integration.service file. Under requires (https://github.com/Tendrl/monitoring-integration/blob/master/tendrl-monitoring-integration.service#L3) we must add grafana-server.

**Comment by rishubhjain** [comment]
@nthomas-redhat I have gone through service files of other tendrl componenets and I feel there is a need to include grafana-server under "After" as well. https://github.com/Tendrl/node-agent/blob/master/tendrl-node-agent.service#L4
@TimothyAsir Could you guide me what all will be needed so that monitoring-integration starts only after grafana-server is up and running?

**Comment by nthomas-redhat** [comment]
@rishubhjain ,you need both `Requires` and 'After'. Requires ensures that dependency requirements are met After ensures the ordering. Please have a look at https://www.freedesktop.org/software/systemd/man/systemd.unit.html for more details

**Comment by rishubhjain** [comment]
@nthomas-redhat ack, will include it in the tendrl-monitoring-integration.service file

**Comment by r0h4n** [comment]
@nthomas-redhat "Requires" ensures that tendrl-monitoring-integration does not start unless grafana-server.service is "active" 

"After" doesnt care of grafana-server.service is "active" or "failed", it will still start tendrl-monitoring-integration

Source: https://serverfault.com/questions/812584/in-systemd-whats-the-difference-between-after-and-requires

**Comment by rishubhjain** [comment]
@nthomas-redhat @r0h4n Thankyou, closing the issue
