### ISSUE TITLE
Status panel in Grafana is generation assembling Problem.

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/monitoring-integration#67]
The Status panel plugin creates problem while assembling of panels.

The problem is in a plugin I have arranged the panel's accordingly So UI doesn't don't look bad. It's not matching the UX because of that Status Panel Issue.

**Comment by cloudbehl** [comment]
@julienlim @mcarrano ^^

**Comment by julienlim** [comment]
@cloudbehl Can you add a screenshot of what you're referring to?  It's hard to comment otherwise.  Thanks.

**Comment by cloudbehl** [comment]
@julienlim The Issue is resolved now with the latest build of grafana
