### ISSUE TITLE
New volume shows up in Tendrl UI but not in Graphite, nor Grafana

### ISSUE THREAD

**Issue by julienlim** [Tendrl/monitoring-integration#74]
I've a Gluster (glusterfs 3.12.0) cluster being monitored via Tendrl.  When I imported the cluster, I had 1 volume (distrepvol), and this could easily be seen in the Tendrl UI, Graphite and Grafana.  

However, when I just added another Gluster volume (vol2), I can it in the Tendrl UI, but the newly added volume did not get picked up automatically by Graphite, nor Grafana.

Tendrl UI screenshot showing 2 volumes (distrepvol and vol2):
![screen shot 2017-09-07 at 11 53 59 am](https://user-images.githubusercontent.com/5589919/30173278-1e7e4bf8-93c5-11e7-87f0-c2b351af368e.png)

Grafana screenshot showing the distrepvol (and no other volumes)
![screen shot 2017-09-07 at 12 08 21 pm](https://user-images.githubusercontent.com/5589919/30173336-4543f8c8-93c5-11e7-8bb7-7af34c850185.png)

@Tendrl/tendrl-core @Tendrl/qe @Tendrl/tendrl_frontend

**Comment by cloudbehl** [comment]
@julienlim can you check if monitoring integration service is running properly? Also, can you check if graphite has the values for the new volume?

**Comment by julienlim** [comment]
@cloudbehl graphite did not have any values when I checked yesterday for the new volume, but I'll plan to restart the tendrl-monitoring-integration service and check again later.

**Comment by cloudbehl** [comment]
@julienlim Can you verify with new build and if fixed please close this Issue.

**Comment by nthomas-redhat** [comment]
@julienlim , We have verified this issue and hence closing this. if find it again, please re-open the issue
