### ISSUE TITLE
monitoring-integration_logging.yaml not touched after service reload

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/monitoring-integration#78]
```/etc/tendrl/monitoring-integration/monitoring-integration_logging.yaml``` is part of tendrl-monitoring-integration and it is marked as configuration file in rpm package.

But if I try to do:
```
systemctl reload tendrl-monitoring-integration
```
then 
```
/etc/tendrl/monitoring-integration/monitoring-integration_logging.yaml
```
is not reloaded.
This configuration file should be removed from package if it is not used *OR* it should be reloaded during ```systemctl reload```
```
tendrl-monitoring-integration-1.5.1-1.el7.centos.noarch
```

**Comment by rishubhjain** [comment]
@mkudlej ack, as per discussion with @r0h4n  and @GowthamShanmugam I will remove the monitoring_integration_logging.yaml file as it is not needed

**Comment by GowthamShanmugam** [comment]
Tendrl/monitoring-integration#134

**Comment by rishubhjain** [comment]
Is this tested ?

**Comment by GowthamShanmugam** [comment]
@rishubhjain yes

**Comment by rishubhjain** [comment]
@mkudlej This issue has been addressed and resolved, Please verify and close the issue

**Comment by mkudlej** [comment]
Conf file was removed and is no longer in tendrl-monitoring-integration-1.5.2-20170925T072405.6f3f855.noarch
