### ISSUE TITLE
Grafana Dashboard Labels misleading

### ISSUE THREAD

**Issue by julienlim** [Tendrl/monitoring-integration#79]
The default Grafana dashboards are wordy and also somewhat misleading.

![screen shot 2017-09-11 at 12 06 07 pm](https://user-images.githubusercontent.com/5589919/30284931-731fc092-96ea-11e7-9cdd-f5115a5757d3.png)

* Why do we need to prefix the dashboards with "Tendrl - Gluster -?"
* If you're only see 1 host at a time for the dashboard, why is it called "Tendrl - Gluster - Hosts?"  The same applies to Bricks and Volumes?
* What is "Tendrl - Gluster - At - A - Glance" supposed to mean?  What is it showing?

Dashboard labels should be representative of what it displays.  Instead I might suggest we try:
Cluster

- Cluster Dashboard   or   Cluster Overview   or   Cluster At-A-Glance
- Host Dashboard   or   Host Overview   or   Host At-A-Glance
- Volume Dashboard   or   Volume Overview   or   Volume At-A-Glance
- Brick Dashboard   or   Brick Overview   or   Brick At-A-Glance

@Tendrl/qe @anivargi @cloudbehl

**Comment by nthomas-redhat** [comment]
@julienlim ,  Is this still an ask? Can we continue with the current scheme of things?

**Comment by cloudbehl** [comment]
@GowthamShanmugam ^^

**Comment by julienlim** [comment]
@nthomas-redhat @GowthamShanmugam @cloudbehl @r0h4n 

Removing the "Tendrl - Gluster - " will make branding efforts easier.

Above recommendations still stand.  I still strongly recommend to simplify this to (without plural on Cluster, Host, Volume, and Brick):

Cluster Dashboard, Host Dashboard, Volume Dashboard, and Brick Dashboard

**Comment by julienlim** [comment]
Note the screenshot examples with the Dashboard labels changed in https://github.com/Tendrl/monitoring-integration/issues/383#issuecomment-375404961.

**Comment by nthomas-redhat** [comment]
Closing the as the fix is already merged
