### ISSUE TITLE
Gluster - Host At-A-Glance (Grafana host dashboard): Label and y-axis metric changes

### ISSUE THREAD

**Issue by julienlim** [Tendrl/monitoring-integration#91]
In reviewing the "Gluster - Host At-A-Glance" dashboard, to make some of the charts more clear to the user, I'd suggest the following modifications:

Label Changes:
* Memory —> Memory Utilization
* Swap —> Swap Utilization
* CPU —> CPU Utilization
* Dropped Packets —> Dropped Packets Per Second
* Errors —> Errors Per Second

“Disk Load” Chart 
* Can we change the metrics shown to bps, kbps, Mbps, etc. on the y-axis (instead of k and Mil)?

“Disk IO” Chart
* Can we show ms (for milliseconds) on the y-axis?

“Throughput” Chart
* Can we include the unit on the y-axis or to the Chart label?  From reading https://github.com/Tendrl/documentation/wiki/Metrics, I can’t tell if this is bytes/sec.  If bytes/sec, can we include this on the y-axis?  Or include it into the Chart Label.

“Dropped Packets” Chart
* What is pps on the y-axis?  Is it Packets per second?  If so, maybe we should add it to the Chart label, i.e. “Dropped Packets per Second.”  If added to the Chart, please remove pps on the y-axis (as it would be redundant).

@Tendrl/qe @cloudbehl

**Comment by cloudbehl** [comment]
@julienlim Issue's has been addressed, please verify.

**Comment by rishubhjain** [comment]
@julienlim PR -> https://github.com/Tendrl/monitoring-integration/pull/122 solves this issue, please verify

**Comment by rishubhjain** [comment]
@nthomas-redhat This issue is resolved, Please verify and close the issue

**Comment by julienlim** [comment]
Verified.
