### ISSUE TITLE
Historical data for graphs in Grafana older than 24 hours are missing

### ISSUE THREAD

**Issue by dahorak** [Tendrl/monitoring-integration#95]
There are no data in graphs in Grafana (and Graphite) older than 24 hours.

What's the default time for keeping historical data for graphs? (for example Throughput Trend, Ping Latency Trend, Memory, CPU, Swap, Capacity Utilization Trend and others)

Most of the graphs doesn't make much sense for such short period.

Following *Throughput Trend* is from cluster running for more than two days, but there are no data older than 24 hours.
![historical_data_grafana](https://user-images.githubusercontent.com/4759779/30371429-d42172d2-987a-11e7-8568-3508cc85a9a7.png)

**Comment by cloudbehl** [comment]
linking: https://github.com/Tendrl/monitoring-integration/issues/59

**Comment by rishubhjain** [comment]
@dahorak The changes are in and the PR are merged, can you verify if the issue is solved?
@anmolbabu Any comments from your side?

**Comment by anmolbabu** [comment]
>@anmolbabu Any comments from your side?

Nope

**Comment by dahorak** [comment]
I've tried to find some specification related to this topic (length of historical data in graphs), but didn't find anything (maybe just miss it), so if following questions are already answered, please redirect me to the right doc.

Would it be possible to configure the time for keeping historical data somehow slightly more cleverly? I mean, that for some kind of data is 180 days definitely enough (and maybe even too much), but for example for Volume space utilization graphs it would make sense to keep historical data for years. Those trends might be very helpful with expansion plans.

I think, it will also make sense to keep older data more sparse. For example, if the data are collected each minute, it make sense to keep them for one week, then one month keep data with interval 5 minutes, one year keep data with interval 1 hour and "forever" keep average data from whole day (or something like that).

**Comment by rishubhjain** [comment]
@anmolbabu @cloudbehl @nthomas-redhat Please comment on @dahorak 's comment

**Comment by nthomas-redhat** [comment]
@dahorak , This is an RFE, Can you file a different issue to track this?

**Comment by dahorak** [comment]
@nthomas-redhat  RFE created: https://github.com/Tendrl/monitoring-integration/issues/173

**Comment by dahorak** [comment]
I'm not able to verify, that the data are kept for whole 180 days, but they are not deleted after 24hours (I can see data few days old). So I would consider this as verified.
